### ISSUE TITLE
cdn for 3.0 return 404

### ISSUE THREAD

**Issue by boynet** [greensock/GSAP#317]
the urls generated from the docs return 404:
* go to https://greensock.com/docs/v3/Installation#cdn

**example:**
> https://cdnjs.cloudflare.com/ajax/libs/gsap/3.0.0/gsap.min.js
> https://cdnjs.cloudflare.com/ajax/libs/gsap/3.0.0/Draggable.min.js

**Comment by jackdoyle** [comment]
Yep, the CDN takes some time to get updated. Sorry. Hopefully those will be live within a matter of hours, depending on CDNJS. They've already merged the pull request, so I'd expect the files will be making their way to the servers soon. Thanks for your patience.

**Comment by jackdoyle** [comment]
Super weird. Cloudflare is usually updated within like 15-20 minutes of us pushing up to Github...but it is cruising past 36 hours now and...no love. We tried reaching out to Cloudflare folks and nobody is answering. Odd because GSAP was apparently the #1 most requested library in October. 

For now, we're recommending that folks use jsdelivr - https://www.jsdelivr.com/package/npm/gsap

The main GSAP file is at: 
https://cdn.jsdelivr.net/npm/gsap@3.0.1/dist/gsap.min.js

Sorry for the delay. This is highly unusual for Cloudflare. The CDNJS folks are on top of things and their repo is fully updated, but apparently there's a problem right now with actually getting Cloudflare to update their CDN. Hopefully they'll get it squared away soon.

**Comment by jackdoyle** [comment]
This was finally resolved and the files are live on the CDN. Thanks for your patience.
