### ISSUE TITLE
Where is gsap.ticker.useRAF?

### ISSUE THREAD

**Issue by MichaelChistyakov** [greensock/GSAP#327]
https://greensock.com/docs/v3/GSAP/gsap.ticker

In docs there is useRAF method, but I can't find it in newest gsap.

**Comment by ZachSaucier** [comment]
Hey Michael,

`useRAF` has been removed from GSAP 3 because we didn't feel that it was necessary. GSAP will automatically fall back to using `setTimeout`s if necessary. 

Sorry, we're still working on the docs. I'll update that page.

Is there a particular use case that you need it for?

**Comment by MichaelChistyakov** [comment]
Hm, ok.

Yes. Very special case: I'm working on site that shows 'unactive' indicator when window is blured. Indicator has simple scale-in and fade-in animation (`TweenMax.fromTo(..)`) when window loses focus (both on desktop and mobile devices). I used fallback to `useRAF(false)` when window loses focus just because animation works well in this case. But without `useRAF(false)` animation was buggy.

So if it is possible it will be great if you leave this method imho.

**Comment by MichaelChistyakov** [comment]
Zach, sorry for offtop, but I found a strange animation behavior.

Take a look please: https://codepen.io/michaelchistyakov/pen/VwwVgej

As I expect second call to gsap.to should fade boxes to 'alpha: 1' after 2 seconds of first animation, rewriting first alpha animation. I mean I expect that first two seconds I will see slow fade-in and moving to top and then quick fade-in without breaking moving.

Testing with 'overwrite' option of gsap.to shows next results:

'no overwrite': boxes blink after 2 seconds and then returns to alpha 0.25
'overwrite: true' option will break moving top top.
'overwrite: false' is equal to 'no overwrite', but I expect that there will be no blinking.

I'm doing something incorrect or it is bug?

I think the best and correct way is to overwrite only alpha animation without breaking motion in case when no 'overwrite' option is specified.

If I specify 'overwrite: true' all previous animations should be ignored.

If I specify 'overwrite: false' (in this case) I should not see any blinks white first animation is working.

Also you may try to implement smart 'overwrite': gsap.to(..., { overwrite: 'alpha,rotationX'}) or something like this.

**Comment by ZachSaucier** [comment]
That's the intended behavior. You can set `overwrite: "auto"` to get what you want. By default in GSAP 3, `overwrite` is set to `false`.

I'm kind of surprised that `overwrite: "alpha"` doesn't work. @jackdoyle do you know why that is?

**Comment by MichaelChistyakov** [comment]
Zach thank you! 'overwrite: auto' works great. But it is strange that by default gsap 3 uses 'overwrite: false'. Intuitively, I think it would be more correct to use 'auto' by default.

**Comment by ZachSaucier** [comment]
It was changed in GSAP 3 so that people know exactly what is going on in their animations. You can change the default by declaring `gsap.defaults({overwrite:"auto"});`.

**Comment by MichaelChistyakov** [comment]
Zach, one more troubble: https://codepen.io/michaelchistyakov/pen/wvvQNZQ

'stagger' breakes alpha animation of third box.

**Comment by ZachSaucier** [comment]
Huh. @jackdoyle will have to look at that.

Side note, the string based version of eases uses the form `power2.out`. But that's the default so you don't even have to include it.

**Comment by MichaelChistyakov** [comment]
@ZachSaucier I like to see in code exactly what is going :)

One more example: https://codepen.io/michaelchistyakov/pen/jOOQJqN

I dont understand if I doing something wrong and why I have strange console warnings.

**Comment by jackdoyle** [comment]
> when window loses focus (both on desktop and mobile devices). I used fallback to `useRAF(false)` when window loses focus just because animation works well in this case. But without `useRAF(false)` animation was buggy.

Years ago, setTimeout() wasn't affected by the window being hidden/inactive, but most modern browsers throttle those calls just like requestAnimationFrame(), so your "solution" wouldn't really work anyway. That's one of the reasons we eliminated useRAF() on the ticker (plus it simplifies the API and helps reduce file size). 

> 'stagger' breaks alpha animation of third box.

Ah, very interesting edge case. I believe that should be fixed in the upcoming release which you can preview here: https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

> Side note, the string based version of eases uses the form `power2.out`. But that's the default so you don't even have to include it.
For the record, the default is "power1" (Power1.easeOut). And no, we didn't want to do the toLowerCase() thing. Again, we're trying to nudge people into good, consistent habits and make the API consistent as well. 

> One more example: https://codepen.io/michaelchistyakov/pen/jOOQJqN
> 
> I don't understand if I doing something wrong and why I have strange console warnings.
The problem is that you're looping through childNodes instead of children - See the notes at https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes: 

> childNodes includes all child nodes, including non-element nodes like text and comment nodes. To get a collection of only elements, use ParentNode.children instead.

When GSAP encountered one of the text nodes (which isn't a regular node, so it doesn't have a "style" for example), it noticed that those properties didn't exist on it and issued that warning. That's a GOOD thing - it exposed a problem in your code :) Again, switch to "children" instead and you'll be fine. 

Does that clear everything up?

**Comment by MichaelChistyakov** [comment]
@jackdoyle thank you! 'childNodes' is my mistake🤦‍♂

gsap-latest-beta.min.js works great with 'stagger-alpha' test. So I'll just wait for new version.

**Comment by MichaelChistyakov** [comment]
Is it possible to remove console warnings when empty array is passed to gsap.to?

**Comment by jackdoyle** [comment]
> Is it possible to remove console warnings when empty array (or NodeList) is passed to gsap.to? Or add defaults option for this behavior? Or change warning text to make it more understandable.

Sure.

```javascript
gsap.config({nullTargetWarn:false});
```

**Comment by MichaelChistyakov** [comment]
Thank you! Dont forget to update docs :)

https://greensock.com/docs/v3/GSAP/gsap.config()
nullContentWarn / nullTargetWarn

**Comment by jackdoyle** [comment]
I updated it immediately after posting here, but thanks for the reminder.

**Comment by MichaelChistyakov** [comment]
Jack, thanks for your work! I have been using your developments since the days of Flash and ActionScript 2.0.

Tell me when to expect gsap updates? At the moment, I see the wrong behavior not only with the stagger, but also with delayedCalls. Beta version works fine.

**Comment by OSUblake** [comment]
>But it is strange that by default gsap 3 uses 'overwrite: false'. Intuitively, I think it would be more correct to use 'auto' by default.

I agree. In all my years of using of gsap, I have never once had an overwrite issue. Now I'm getting them all the time, having to constantly change it to "auto" or true. I'd be nice to go back to "auto". `overwrite: false` is just not intuitive to me at all.

**Comment by jackdoyle** [comment]
> In all my years of using of gsap, I have never once had an overwrite issue. Now I'm getting them all the time, having to constantly change it to "auto" or true.

That means you're writing animations that conflict all the time. Seems like it should be relatively rare out in the wild. I know for sure that plenty of people ran into challenges with "auto" mode because they never even knew what overwriting was or that they were creating conflicts (that GSAP was automatically attempting to "fix" for them, but then inevitably they'd rewind an animation and see that it didn't play the same the nth time through and get confused/frustrated). Having folks opt in to overwriting ensures that they're explicit about their intent and minimizes the chances of confusion but if enough people run into issues like this we could certainly consider a change. But there's also a performance penalty with auto because it has to search the whole system for conflicting tweens the first time each tween renders. Not the end of the world, but not ideal either. I'd much rather encourage people to be explicit about their intent and opt-in instead of being surprised by overwriting that they never requested. See what I mean?

**Comment by OSUblake** [comment]
>That means you're writing animations that conflict all the time.

Probably. It happens it a lot of when doing interactive stuff. I'd imagine that I'm not the only one that is having hard time getting used to overwrite false.
