### ISSUE TITLE
the number  is not update accurate of v3

### ISSUE THREAD

**Issue by yuyoo0508** [greensock/GSAP#329]
var a={b:0}; gsap.to(a,10,{b:8700900,onUpdate:()=>{console.log(a.b)},roundProps:'b'})
the prop 'b' is not update accurate and the end value is wrong

**Comment by ZachSaucier** [comment]
Hey yuyoo. This issue was brought up [on our forums](https://greensock.com/forums/topic/21902-gsap-tweening-between-numbers-bug/) and has been fixed in the latest beta version: https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

Side note: The new SnapPlugin in GSAP 3 has replaced the functionality of roundProps. See [the release notes](https://greensock.com/3-release-notes#snap) for details.
