### ISSUE TITLE
vue-cli3 with gsap. Invalid autoAlpha tween of 0 Missing plugin? gsap.registerPlugin()

### ISSUE THREAD

**Issue by Innei** [greensock/GSAP#336]
I used vue-cli3 to create Vue project. In the development, this code didn't throw an error or warning.

```js
this.tweeners[i]  // TimelineMax Object
          .fromTo(
            '.static-container',
            1,
            { autoAlpha: 0, filter: 'blur(5px)' },
            { autoAlpha: 1, filter: 'blur(0px)' }
          )
          .to(scenesElement, 1, { autoAlpha: 1 })
          .fromTo(
            '.static-container',
            1,
            { autoAlpha: 1, filter: 'blur(0px)' },
            { autoAlpha: 0, filter: 'blur(5px)' }
          )
```

In dev, it works. But, I build this project, but it didn't work. and throw more warning.

```
gsap-core.js:83 Invalid autoAlpha tween of 0 Missing plugin? gsap.registerPlugin()
gsap-core.js:83 Invalid filter tween of blur(5px) Missing plugin? gsap.registerPlugin()
```

If I want to used Vue-cli3 to build this project, (I didn't modify any vue-cli config), How can I modify config or webpack, to achieve the result I want.

**Comment by jackdoyle** [comment]
Hm, it sounds like your build process is applying aggressive tree shaking that's dumping CSSPlugin. In the upcoming release, we've added some additional protections against that but in the mean time you could try importing CSSPlugin and then do gsap.registerPlugin(CSSPlugin) just so that your code references it somewhere (protecting it from tree shaking). But again, in the upcoming release (probably in the next week or two), this extra step won't be necessary.

**Comment by Innei** [comment]
I add two lines just now, Okay, it works now.

```
import { gsap, CSSPlugin } from 'gsap/all'
gsap.registerPlugin(CSSPlugin)
```

Thanks.

**Comment by AideaCompany** [comment]
I love you bro <3

**Comment by idanasher** [comment]
How to i do it in HAXE openfl project ?

I keep getting 
"invalid property scaleX set to 1 Missing plugin? gsap.registerPlugin()" runtime warnings

**Comment by ZachSaucier** [comment]
> How to i do it in HAXE openfl project ?

Never heard of it.

> I keep getting
> "invalid property scaleX set to 1 Missing plugin? gsap.registerPlugin()" runtime warnings

Maybe the CSSPlugin isn't being included?
