### ISSUE TITLE
use GSDevTools in gsap v3

### ISSUE THREAD

**Issue by hereiscasio** [greensock/GSAP#339]
i have tried, but it just not works

( include below scripts in Codepen.io will not work as expect )

https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/GSDevTools.min.js?r=100
https://cdnjs.cloudflare.com/ajax/libs/gsap/3.0.1/gsap.min.js

**Comment by hereiscasio** [comment]
ok, i found the proper link of GSDevTools for gsap v3, 

but ... 

it seems like, 
i shouldn't post that link public at here

**Comment by jackdoyle** [comment]
Sorry about any confusion there. And yes, it's okay to share this link below because it only works on codepen.io, but I really appreciate your sensitivity about not making it easy for people to use it without signing up for Club GreenSock: 
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/GSDevTools3.min.js

Happy tweening!
