### ISSUE TITLE
Manual tick(update)

### ISSUE THREAD

**Issue by Gaikov** [greensock/GSAP#350]
I use custom opengl renderer and I would like to have ability to call tick(update) manually before my scene is rendered.

**Comment by ZachSaucier** [comment]
Hey Gaikov. GSAP updates every requestAnimationFrame. 

Have you experienced any issues with the way that GSAP functions? If so, can you please try to recreate the error in a minimal demo and share it with us?

**Comment by jackdoyle** [comment]
You could unhook the ticker from the main function that updates the globalTimeline like this: 
```javascript
gsap.ticker.remove(gsap.updateRoot);
```
And then you can call gsap.updateRoot(time) manually and feed in the time you want. Is that what you're looking for?

**Comment by Gaikov** [comment]
For example I have pause in my game and when I press pause I do not want to call tick(update) for tweens

**Comment by jackdoyle** [comment]
Oh! That should be pretty easy. There are a lot of options, actually. Check out the exportRoot() method: https://greensock.com/docs/v3/GSAP/gsap.exportRoot()

If you truly want to stop EVERYTHING (meaning delayedCalls too), you could pause the [globalTimeline](https://greensock.com/docs/v3/GSAP/gsap.globalTimeline) or alter its timeScale(). 

Or just build your animations in their own Timeline so that you have total control of that, like you can pause(), resume(), alter its timeScale(), etc. 

It's extremely rare that anyone would actually need to mess with the global ticker and updateRoot() stuff.
