### ISSUE TITLE
Objects with a .length property or getter are not handled well

### ISSUE THREAD

**Issue by naranjamecanica** [greensock/GSAP#352]
I'm using ``gsap.to`` on a custom input text field made in PixiJS and this object has a getter named ``length``. 

 ```
 public get length(): number {
    return this.field.length;
 }
```

Tweening this object results in a warning ``GSAP target [object Object] not found. https://greensock.com`` . 

Off course I can rename my getter, but maybe the detection used is not robust enough. 👍

**Comment by jackdoyle** [comment]
That's tricky indeed because it's very common for people to pass in the result of a document.querySelectorAll() or a jQuery object which are basically array-like containers of other targets. So GSAP looks for a "length" property. If it's non-zero, it'll also check to see if the first element is an object. So the tricky part here is if length is exactly 0, there aren't really other checks I can think of that'd work. Let me know if you can think of any that'd work with all array-like containers like the ones I mentioned above. 

In the next release of GSAP, I can implement a solution that allow you to just wrap your object in an array, like: 
```javascript
gsap.to([target], {...});
```
You can preview that upcoming release with the fix in place at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js - better?

**Comment by naranjamecanica** [comment]
I understand, I don't know an efficient simple way to check for array like object without taking in all exceptions. Right know I can not check the new build easily since i use a custom build system, but wrapping it in a array is a good solution we can use! 👍
