### ISSUE TITLE
 error TS4025: Exported variable 'Tween' has or is using private name 'gsap.core.Tween'.

### ISSUE THREAD

**Issue by naranjamecanica** [greensock/GSAP#353]
I'm using a wrapper around your library in Typescript. 
````
export const Tween = (target: {}, duration: number = 0, properties: gsap.TweenVars, settings?: gsap.TweenVars): gsap.core.Tween => {
  [...]    
  return gsap.to(target, vars);
}
````
When I export and generate declaration files for Typescript I get to following error:
> error TS4025: Exported variable 'Tween' has or is using private name 'gsap.core.Tween'.

Is it possible to export a `Tween` const from the types like you do with `TweenMax` and `TweenLite` etc in `gsap-core.d.ts`?

Something like:

`export class Tween extends gsap.core.Tween {}`

**Comment by OSUblake** [comment]
Tween and Timeline aren't exported because we thought it might cause name conflicts with other libraries.
https://github.com/greensock/GSAP/issues/318#issuecomment-553250162

There is a global type for a Tween,  `GSAPTween`. But I don't know if that will help you as I'm not familiar with that error.

And you should be able to augment the types with your own d.ts file. Something like this.
```ts
declare module "gsap/gsap-core" {
  export class Tween extends gsap.core.Tween {}
}
```

**Comment by naranjamecanica** [comment]
Thanks the augmenting worked! Had some issues, but that was because my definition file was called `gsap.d.ts`.
