### ISSUE TITLE
tl.tweenTo() vars

### ISSUE THREAD

**Issue by myzonjkee** [greensock/GSAP#357]
Hello,
here is an [example](https://codesandbox.io/s/gsap-tweento-m7p3m))

I have a `timeline` where I move an object from A to B in 3s.
I also have 3 buttons (Play, TweenToA and TweenToB).
And when I'm clicking for example on the TweenToB button I expect to move the object in 1s with a custom ease to B, but it seems like `tweenTo()` ignore `vars` that I passed to it)

Thank you for your help!

**Comment by jackdoyle** [comment]
Almost the entire point of tweenTo() is to have the engine calculate the appropriate duration given the distance between the starting time and ending time. If you don't need that, you can just do a normal tween of the playhead (either time, totalTime, or progress) like this:
https://codepen.io/GreenSock/pen/78bb73dfc3095566d213af9c73fe30ff?editors=0010

But I do see that the **ease** isn't getting applied properly, and that'll be fixed in the next release which you can preview at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

I'll also add code to look for any duration you provide in the vars and have that override the auto-calculated tween, so it should fix your scenario completely. 

And here's the demo with it working: https://codepen.io/GreenSock/pen/e8ab06845a9fc370cbcaa1d99499799b?editors=0010

**Comment by myzonjkee** [comment]
Thank you!
