### ISSUE TITLE
Css plugin first animation forced reflow performances

### ISSUE THREAD

**Issue by minimit** [greensock/GSAP#364]
Hello I've a problem with some complex animations, the first time they execute they force the reflow of all the page for 200 milliseconds, since it's a complex page.
![image](https://user-images.githubusercontent.com/817279/75166489-38b44980-5724-11ea-8c40-f6a2fd2bc336.png)

Sequential animations instead are very fluid.

**Comment by jackdoyle** [comment]
It's very difficult to troubleshoot blind - can you provide a reduced test case that demonstrates the issue? It sounds like maybe you've got a lot of set() calls firing immediately. Have you tried setting gsap.defaults({lazy:true})?

**Comment by minimit** [comment]
You can see a reduced test here
https://codepen.io/minimit/pen/dyoNaod
https://cdpn.io/minimit/debug/dyoNaod/

Click the document to make the animation, you can see that the first 2 clicks active animation start with a little delay it's like a little jump at the start of the animation (it's more visible on complex webpage).

**Comment by ZachSaucier** [comment]
@minimit Thanks for the demo! 

It looks like the majority of the lag and jump is due to image decoding. In other words, this is because you haven't displayed them yet so the browser doesn't parse them. Then you try to start your animation but the images haven't been parsed yet. So since that takes some time then it causes a bit of "lag". 

Probably the most easy way to fix this is to not use `display: none` on the parent but instead use `visibility: hidden`. Just making that one change causes the changes in rastering you see below.

With `display: none`:
![image](https://user-images.githubusercontent.com/3966722/75253390-7492f180-57ac-11ea-97fe-68cb80b16f02.png)

With `visibility: hidden`:
![image](https://user-images.githubusercontent.com/3966722/75253449-8d030c00-57ac-11ea-9897-8b2f22a26424.png)

**Comment by minimit** [comment]
Maybe there was a little bit of that, but with my slow mac i see a jump in the initial animations with your fix still. I've updated the demo can you check again if you see the jump of the first animations? It's also more evident cause I use 'expo.out' easing, if you put 'expo.inOut' the jump is not noticeable

**Comment by ZachSaucier** [comment]
It looks like the issue is still image decoding and layer compositing, not anything related to GSAP:
![image](https://user-images.githubusercontent.com/3966722/75272936-d95e4400-57cc-11ea-8f46-c4fc59a06eb6.png)

The GSAP-related code takes less than 7ms on my device on first play. 

You could try using `will-change` to limit that compositing. 

Maybe Jack will see something that I'm missing.

**Comment by jackdoyle** [comment]
Yep, this doesn't look GSAP-related at all. You've got a bunch of very large (2000x2000) images loading and it's hard on the browser to decode, resize, and display those. On top of that, you've got a lot of percentage-based values that require the browser to do a lot of calculations. 

Pre-layerizing things as Zach said would be smart, but it's probably not gonna solve all the problems. You're just asking a lot of the browser. Again, this is totally unrelated to GSAP. 

I also noticed that you've got a 1-second delay between clicking and the dispatching of the event which feels quite odd as a user - it makes the whole UI feel unresponsive. 

Lastly, I see that in several places you do a gsap.set() and then a gsap.to() on the same element - you could simply do a single gsap.fromTo() to make it more concise. 

If you want to let the browser have a little breathing room when doing all that image decoding and compositing, you could consider adding a slight delay to your tweens. 

Happy tweening!

**Comment by minimit** [comment]
In the production code I've tried without display: none, without object-fit, with will-change, without percentage transforms, nothing seems to work, there's still a little jump in **on** animation.

The only way is to change easing (not a `.out` easing) or add `delay: 100` on **on** animations, it fixes it.

Thanks again
