### ISSUE TITLE
Timeline duration setter has no effect in version 3.2.4

### ISSUE THREAD

**Issue by sudara** [greensock/GSAP#372]
Hi there!

It looks like calling the timeline duration setter in version 3.2.4 is broken. 

The following works on version 3.1.1 but fails on 3.2.4:

https://codepen.io/sudara/pen/abOGjaX

**Comment by ZachSaucier** [comment]
Thanks for the catch! It is indeed a bug but it has been brought to our attention already and is fixed in the latest beta file which you can access here: https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

The next minor version with this fix in it should be released within the next week.

**Comment by sudara** [comment]
Thanks @ZachSaucier!

We use the npm modules, and it doesn't look like greensock does betas on npm, but not to worry — in the meantime we've replaced our `.duration` calls with `timeScale` calls :)

**Comment by ZachSaucier** [comment]
You can npm install this tarball to get it into your project 🙂 
https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-beta.tgz

**Comment by sudara** [comment]
@ZachSaucier Oh, woah, ok! Thanks!

**Comment by ZachSaucier** [comment]
Happy to help!

**Comment by jackdoyle** [comment]
This should be resolved in the latest release (3.2.5). Thanks for pointing it out!
