### ISSUE TITLE
`clearProps` causes the MutationObserver API to be notified of a removed node

### ISSUE THREAD

**Issue by chadwickellis** [greensock/GSAP#375]
I frequently make use of the MutationObserver API to bind Javascript functions to nodes, initialising or destroying them based on whether they have been injected in or removed from the DOM.

With reference to this [JSFiddle test case](https://jsfiddle.net/chadwickellis/mLn3ky1d/latest/), if I were to animate a fixed position element's transform property using the CSSPlugin and call `clearProps`, the MutationObserver API receives a notification that the element has been removed.

I can see that in its simplest form `clearProps` sets the elements `cssText` property to `null`; however, if I were to call this manually as opposed to using `clearProps` the MutationObserver API is no longer notified that the element has been removed. Unfortunately this means that, to my knowledge, the CSS transformations remain cached and upon resizing the viewport any `xPercent` or `yPercent` tween will no longer be accurate.

**Comment by jackdoyle** [comment]
Ah, I think I see what you mean, but it has nothing to do with the transformation cache. If you think something is becoming inaccurate, please provide details but the MutationObserver was getting triggered because CSSPlugin sensed that there was no offsetParent on the target, and no transform applied which often means it's not in the DOM, so CSSPlugin temporarily added it to the documentElement in order to ensure accurate measurements. It's a cross-browser compatibility thing. For example, if display: none is set on an element, the transforms won't be reported accurately, so GSAP handles that under the hood for you. 

Anyway, in your case it wasn't really necessary to do that temporary swap into the DOM. I improved the code to exclude a case like that. You can see a preview of the upcoming release at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js. 

Thanks for letting us know. And again, if you're having issues with a transform cache being inaccurate, I'd love to hear more details about that. Of course if you clearProps: "all", that'd clear the transforms too, so I wouldn't expect them to be cached. I may have misunderstood your comment though.

**Comment by chadwickellis** [comment]
Thank you for getting back to me on this one Jack, I have replaced my local v3.2.6 with the v3.0.0@beta version you sent across. I can confirm that this beta version resolves the issues I was facing with the MutationObserver API. Are you able to forecast when you are likely to take this version of out of beta and publish it to npm?

I will continue to test this beta version over the coming days before getting back to you regarding any possible issues that I might be facing with the transform cache.

**Comment by jackdoyle** [comment]
I can't provide a specific date for the 3.3.0 release, but I'd guess maybe a couple of weeks. We're working on something pretty cool that'll be in that release :)

**Comment by chadwickellis** [comment]
No worries at all, I'll keep an eye out for the release and revisit this thread if necessary. Thank you for your time again on this!
