### ISSUE TITLE
3.2.6 to 3.3.1 Loss in transitions

### ISSUE THREAD

**Issue by zslabs** [greensock/GSAP#388]
👋 Hi all, as part of https://github.com/gremlin/chaoskit ([demo site](https://chaoskit.netlify.app/)) components like [OffCanvas](https://chaoskit.netlify.app/?path=/story/components-offcanvas--overview) and [Modal](https://chaoskit.netlify.app/?path=/story/components-modal--overview) are using a `x` and `y` properties as part of their timeline, respectively. When upgrading to `3.3.1` I noticed this transition is lost. I also tried using `xPercent` and `yPercent` without any luck, but I may be misunderstanding the point of those properties.

### Reproduction

1. Pull down https://github.com/gremlin/chaoskit
1. Inside of `package.json` upgrade GSAP to `3.3.1`
1. Run `yarn develop` (this will install all deps and fire up a Storybook instance)
1. Visit "Components > OffCanvas" and you'll notice there is no slide transition. You can compare this to the current live version of the demo mentioned above.

Please let me know if I can provide anymore context. Thanks!

**Comment by ZachSaucier** [comment]
Hey zslabs. It'd really help us in figuring out the issue if we didn't have to pull the entire project and filter through all of the irrelevant parts. Can you try to create a more minimal demo of the issue, perhaps in a CodePen or CodeSandbox?

**Comment by zslabs** [comment]
@ZachSaucier Here's a smaller reproduction https://codepen.io/zslabs/pen/qBbOzVR

If you take off the `offCanvas` label attached to each `to` so they move independently, you'll notice there's no issue. If you downgrade the deps in that CodePen to 3.2.6 - things work as they should.

**Comment by ZachSaucier** [comment]
Thanks! That's very helpful. That's definitely a bug and we'll get it fixed ASAP.

**Comment by ZachSaucier** [comment]
Curiously if I change the position parameter to 0.02 it works. But even 0.019 doesn't work.

**Comment by jackdoyle** [comment]
This is one of the reasons we strongly recommend **ALWAYS** setting your transform-related values via GSAP instead of only in CSS. It's fine to _also_ set the initial ones in CSS to avoid FOUC, but when you set them in GSAP too it ensures that the proper values are cached and there's no ambiguity in rotational values. The browser always reports computed transforms as matrix() or matrix3d() which are px-based, thus it's impossible to discern percentage-based values and also rotations become ambiguous (i.e. rotation of 0, 360, 720, etc. are all identical matrices). 

Here's a fork that shows how it resolves things by simply setting the transforms via GSAP: 
https://codepen.io/GreenSock/pen/36449da7dfe34f3dfe7db5a4c8b00295?editors=0010

Let me explain what's going on...

You've got an element nested inside another one that's display: none which causes the browser to mis-report the transforms. Try this in your demo:
```javascript
let el = document.querySelector(".offcanvas-panel");
console.log(window.getComputedStyle(el).transform); // none!
```
There was a "bug" report (not really a _bug_) at https://github.com/greensock/GSAP/issues/375 that we accommodated by changing the kind of check we were doing (instead of checking for a null offsetParent, we checked to see if the element was in the <body>) but in your example that still fails. Elements with position: flex always report a null offsetParent. 

I'll roll back that change in order to resolve the edge case here.

You can test out a preview of the next release (with this fix) here:
https://assets.codepen.io/16327/gsap-latest-beta.min.js

Better? 

> Curiously if I change the position parameter of the second tween to 0.02 it works. But even 0.019 doesn't work.

That's just because when you pad the beginning like that, by the time that second tween renders for the first time, the parent element has had its display set to "block", thus transforms get reported correctly by the browser.

**Comment by jackdoyle** [comment]
And by the way, thanks so much for the reduced test case in CodePen @zslabs ! I know that takes you some extra time but it **really** helps us address it promptly and it ensures we're crystal clear on what the issue is.

**Comment by zslabs** [comment]
@jackdoyle That preview release does indeed resolve that issue! I really appreciate the explanation and the suggestion to move these initial styles to GSAP. I'll definitely do that moving forward. Thanks both for helping with this!
