### ISSUE TITLE
.reverse() timeline bug on v3.4.0

### ISSUE THREAD

**Issue by fcisio** [greensock/GSAP#399]
## Steps to reproduce
1. Use ^3.4.0
2. Create a simple timeline with two call (at start and end)
3. Play it once and again in reverse

```js
const animation = tl
    .call(() => alert('!'))
    .fromTo(node, { backgroundColor: 'red' }, { backgroundColor: 'blue'})
    .call(() => alert('!'))
    .pause()

let open = () => animation.play()
let close = () => animation.reverse(0)
```

## Expected:
Both alerts should be called on play and reverse

## Currently:
Only works properly on play(), reverse() is missing the last call (time wise).

## Observations:
Bug is not present on v3.3.0

**Comment by raulmelo** [comment]
Use tl.reversed( true );
https://greensock.com/docs/v3/GSAP/Timeline/reversed()

**Comment by jackdoyle** [comment]
Hm, @fcisio, I'm struggling to see the problem here. I must be missing something. 

1. After playing all the way to the end and calling the last alert(), I wouldn't expect it to fire again when you reverse(). A callback should play EITHER when the playhead arrives at that spot on the timeline OR when it leaves, not both. Otherwise, you'd get double-calls in various scenarios like yoyos. Trust me - I've dug into this quite deeply over the years and if we did the double-calls, we'd get a lot of complaints. :) 
2. You said that it works differently in 3.3.0, but I can't seem to verify that at all - here's a Codepen that uses 3.3.0 and it appears to work identically: https://codepen.io/GreenSock/pen/20105694f9b334642c567517bdfe9ac8?editors=0010 - can you explain what I'm missing? 

If you want it to fire in both cases, you can simply add a little time (gap) to the end of the timeline so that the playhead can go PAST that spot rather than landing on it exactly and sticking there. Like tl.to({}, {duration:0.001}) at the end.

**Comment by ZachSaucier** [comment]
> 2\. You said that it works differently in 3.3.0, but I can't seem to verify that at all - here's a Codepen that uses 3.3.0 and it appears to work identically: https://codepen.io/GreenSock/pen/20105694f9b334642c567517bdfe9ac8?editors=0010 - can you explain what I'm missing?

That has an added tween at the end. If you comment out the tween `.to({}, {duration:0.001})` you will see that the behavior varies in 3.4 compared to 3.3.x.

**Comment by ZachSaucier** [comment]
I can't reproduce it any longer on the same device... Have you noticed any consistent way to reproduce the difference @fcisio?

**Comment by jackdoyle** [comment]
I'm totally confused - I cannot replicate any odd behavior in either version. 

I removed the .to({}, {duration: 0.001}) in the CodePen. I click "open" and I get the first and second alert. Then I click "close" and I get only the alert from the start. That's exactly what I'd expect. Are you seeing something different? It's identical for me in both 3.3.0 and 3.4.0. As far as I can tell, there's no bug. Can you help me understand where the problem is exactly and how to reproduce?

**Comment by fcisio** [comment]
To me reversing the timeline means exactly that. So if I get bot alerts forward, I should also get both backward.

On my end, it works as described above on v3.3.x, and on v3.4.0 I only get one alert when reversed. I'm mostly reporting inconsistencies I found since I've already found another way to achieve the same result.

The behavior described by @jackdoyle, seems odd to me if it is the desired behavior then it's all good

**Comment by jackdoyle** [comment]
Is there any way you could share HOW to reproduce what you said happens? Like...when you try it in my demo that I provided above, are you able to get different behavior in 3.3 vs 3.4? Is there a trick to seeing it?

As for the "correct" behavior, I understand what you're saying and that's exactly how I used to think a long time ago. I had to put a ton of effort into getting the behavior that you're seeing now because there were a bunch of other "gotchas" that pop up if I were to follow your suggestion (which, again, was precisely what I did years ago). 

Basically what you're advising is that the callback get fired when the playhead arrives **AND** when it leaves a particular spot on the timeline, right? So if it lands on top of the 1-second spot where there's a callback, it'd fire (of course) and then ALSO as soon as it leaves that place to go elsewhere? Can you see how that might be problematic? 

I know the temptation is to only focus on your one particular case and think "well, in my head it makes sense that reverse() would fire both", and I can totally see that, but I've learned over the years that I have to force myself to think through the broader picture and walk through other scenarios as well. If we slap a "fix" on this scenario...it likely has an undesirable effect on various other scenarios. Think of a yoyo tween/timeline for example. Or if you put a label on a timeline at a certain spot that has a callback, and then you seek() there and then play(), would you expect the callback to get fired once or twice? 

Anyway, I'm glad you got a solution in place for what you were trying to do. I'm still super curious about the whole "v3.3 works differently than v3.4" thing. But even if it did, that would likely just mean there was a bug in 3.3 ;)
