### ISSUE TITLE
Scrolltrigger affecting window inner width?

### ISSUE THREAD

**Issue by a-guerrero** [greensock/GSAP#404]
The problem is when using Chrome developer tools device utilities and changing from wider to narrow widths, I have an event listener attached to the resize event and it logs `window.innerWidth` and it prints an older value? I mean, not updated.

Here's the [sandbox](https://codesandbox.io/s/nervous-bogdan-3ss0m?file=/src/index.js).

Here you can see that when the window resize from 400 to 390 `window.innerWidth` is still 400:
![demo](https://user-images.githubusercontent.com/4641859/89476387-26691d80-d750-11ea-9360-e2c5b42b865c.gif)

And I don't know if it's related but one of the demos in the website also prints a weird `window.innerWidth` value when used with Chrome device utilities, [I forked it](https://codepen.io/a-guerrero/pen/wvGvQWd) just to add the event listener and log.

**Comment by jackdoyle** [comment]
@a-guerrero is there something we can help with? Were you saying that you think ScrollTrigger is causing a browser bug or something? 

For what it's worth, when you have pinning enabled, ScrollTrigger must set the width/height of the spacer element(s) to prop things open when switching to position: fixed, and there's an intentional 0.2-second delay between when you stop resizing the window and when ScrollTrigger does its refresh() (which is what recalculates/resizes things). That's to maximize performance. A refresh() is expensive, so it's wasteful to do it constantly on every...single...drag while the window is resizing. So perhaps DevTools is reporting things based on the size of the elements rather than the actual window, and it's doing so before that 0.2-second delay elapses?

**Comment by a-guerrero** [comment]
Yes, I think it shouldn't not affect `window.innerWidth` because then it's a number I can no longer trust for things like handling breakpoints with JS, I understand I can subscribe to a debounced resize event with a delay greater that 200ms but if you depend on a library that uses `window.innerWidth` on a resize event internally then buggy things start to happen.

My current problem is that I have two components, one is for mobile and one for desktop, the desktop one uses ScrollTrigger pinning, so by the nature of my project I'm using a library that subscribes to the window resize event and checks `window.innerWidth` to toggle between this two components and the desktop component keeps persisting because when resizing the value given is outdated. I was suspecting that this might be and issue with Chrome dev tools but it's also happening in my phone when toggling between portrait and landscape.

For now I can fix this by subscribing to debounced resize event and toggling the components by myself instead of using the library but I don't think it's ideal, it was hard to debug what was happening, maybe you should mention this on the docs?.

**Comment by jackdoyle** [comment]
Perhaps I didn't explain it very well...ScrollTrigger **doesn't** alter the window.innerWidth. It can't. That's a read-only property. Any glitch you're seeing with that value must be a browser bug of some kind or maybe a problem with Dev Tools. 

You're welcome to force ScrollTrigger to run a refresh() on every resize event (rather than waiting 200ms after the user is done resizing), like:
```javascript
window.addEventListener("resize", () => ScrollTrigger.refresh());
```
But that isn't something I'd do personally. Up to you, though. I'm curious if that resolves the issue you were running into.

**Comment by a-guerrero** [comment]
It kind of works, but here's the funny thing:
```js
window.addEventListener("resize", (ev) => {
  console.log(window.innerWidth); // Logs outdated value
  ScrollTrigger.refresh();
  console.log(window.innerWidth); // Logs updated value
});
```
This happens both in dev tools and in my Android cellphone. I updated the sandbox. But you're right, `innerWidth` is supposed to be read-only 🤷🏻‍♂️, I agree this not a ScrollTrigger bug.

**Comment by a-guerrero** [comment]
I think I know what the problem is, this is [the W3C specification definition of innerWidth](https://www.w3.org/TR/cssom-view/#dom-window-innerwidth):

> The innerWidth attribute must return the viewport width **including the size of a rendered scroll bar** (if any), or zero if there is no viewport.

I don't know what is the difference between mobile and desktop viewports, but the **scroll** part of the definition seems to be true in mobile and for some reason not in desktop, so for me the solution was very simple, just wrapping the element used as a trigger with a container with the following styles `width: 100%; overflow-x: hidden;` did the trick, now `innerWidth` is always what I expect.

Anyway, I no longer agree that ScrollTrigger is not affecting `innerWidth`, it does via the scroll, at least in mobile.

**Comment by jackdoyle** [comment]
That doesn't sound quite right - the contents of the page wouldn't affect that value. In other words, no matter what ScrollTrigger does, it couldn't possibly affect innerWidth (unless there's a browser bug). Perhaps you're looking for clientWidth? Since that excludes the scroll bar, it would make sense that the number would change based on whether or not a scrollbar is present (which ScrollTrigger could affect). See what I mean?

**Comment by a-guerrero** [comment]
Yep, got confused by definition, [I asked at stackoverflow](https://stackoverflow.com/a/63309963/3841699) and this seems to be a chrome dev tools bug. Thanks @jackdoyle .
