### ISSUE TITLE
reversed: true bug on tween to() after upgrade

### ISSUE THREAD

**Issue by ChriffDev** [greensock/GSAP#407]
Hello,

It seems that after I upgraded a project from 3.2.4 to 3.5.0 my animation won't play if reversed is set to true;

[Demo1 3.2.4](https://codepen.io/Chriiff/pen/xxVVmBe)

[Demo2 3.5.0](https://codepen.io/Chriiff/pen/NWNNoLL)

Not sure if it is a bug or I missed an update on the behavior of Tweens

**Comment by jackdoyle** [comment]
Hi @ChriffDev. Thanks for the minimal demo - very helpful.

From what I can tell, that was actually a bug in the old version which was fixed in 3.3.0. You set reversed: true on an animation whose playhead hadn't moved forward yet at all, and a playhead can never go backwards past the beginning (totalTime of 0). So it just stayed put. That's the correct behavior. 

You might think "but I set repeat: -1, so it should repeat forever in both directions" but repeat controls how many iterations will play in the forward direction. Every animation is placed on a timeline (by default, the global timeline) and must have a start/end time. With repeat: -1, the end time is just REALLY far out ahead (because there are millions of iterations). There are a bunch of logic problems you'd run into if we made repeat: -1 literally be infinite in both directions (I'll spare you the explanation). 

To get the behavior you're after in that demo, all you'd need to do is remove repeat: true, and change the gsap.to() to a gsap.from(). 

Does that clear things up?

**Comment by ChriffDev** [comment]
Hi @jackdoyle. Thanks for the detailed explanation.

It all makes sense, I took a peek in the documentation and it notes the same behavior you're talking about which made it confusing for me since it worked when I used the 3.2.4 version. 

Thanks again, I'll update my code 👍
