### ISSUE TITLE
onStart event never fires for TimelineLite with 0 duration

### ISSUE THREAD

**Issue by bokal1986** [greensock/GSAP#419]
Hello!

I'm using version 3.5.1. I've noticed that TimelineLite doesn't fire onStart event in case the duration is set to 0. 

Please check an example here:
https://codepen.io/gakalo1986/pen/jOqorpY?editors=1111

I believe on gsap version 2.1.3 this wasn't a case.
Thank you!

**Comment by ZachSaucier** [comment]
Hey bokal1986 and thanks for reporting this. There does indeed seem to be a bug where the onStart of timelines with zero duration don't fire. We'll get that fixed in the next release. In the mean time, just apply the onStart to the first tween instead.

By the way, we highly recommend using [the GSAP 3 syntax](https://greensock.com/3-migration/) so that you can make use of GSAP 3's new features. We're confident you'll come to love it even more!

**Comment by jackdoyle** [comment]
Nah, this actually isn't a bug. As the docs state an onStart happens _"when its time changes from 0 to some other value which can happen more than once if the tween is restarted multiple times)"_ but if you've got a zero-duration animation, the playhead can never move away from 0. See what I mean? 

And it has always worked that way, even in v2. 

I'm curious why you'd even want an onStart in a zero-duration tween/timeline.

**Comment by ZachSaucier** [comment]
@jackdoyle How come it works on the tween then?

**Comment by jackdoyle** [comment]
@ZachSaucier I suppose you could call _that_ a bug ;) 

I'll investigate how much is involved in adding that behavior to timelines, but I'm not sure which should be considered a bug.
