### ISSUE TITLE
Timeline onStart/onComplete not being fired correctly when Timeline is empty or has a tween with 0 duration

### ISSUE THREAD

**Issue by manugb** [greensock/GSAP#436]
Hi guys,

I have a Timeline that could be configured with 0 duration Tweens and when I call to Timeline.restart I would expect the timeline to call onStart and onComplete callbacks, but thats is not happening. Also on 3.5.0 only onComplete was called on play and then if you restart the timeline it was not called anymore. And now on 3.6.0 onStart is being called instead of onComplete.

My code depends on the callbacks being called every time the timeline is restarted, what should I do?

**Comment by jackdoyle** [comment]
That was actually a regression in 3.6.0 (it's fixed in the next release). As the docs indicate, an onStart should only fire when the playhead is moved from 0 to something non-zero, but of course that can't happen if you've got a duration of 0. If you really need both callbacks, then don't use a duration of 0. You can make it something like 0.01, for example.

**Comment by jackdoyle** [comment]
Should be resolved in the latest release.
