### ISSUE TITLE
Return the ticker.useRAF() method.

### ISSUE THREAD

**Issue by jkanchelov** [greensock/GSAP#437]
In our current projects, this is the main reason not to migrate to v3 or to go with a custom version to go with the setTimeout implementation.

**Comment by jackdoyle** [comment]
@jkanchelov Can you please elaborate? GSAP v3 will automatically fall back to setTimeout() internally if requestAnimationFrame isn't available, but every modern browser (and even old ones) support requestAnimationFrame which is a much better option anyway. Why would you need ticker.useRAF()? Can you explain your use case? 

Years ago, some browsers allowed setTimeout() to function normally even in hidden tabs which was one reason people wanted that, but virtually all modern browsers as far as I'm aware have switched to throttling down setTimeout() on hidden tabs too, so there's really no benefit whatsoever. Perhaps you know of something different?

**Comment by apelev** [comment]
Hello @jackdoyle. Our games are event based with events coming from server and it is required for the game to switch states at these events. If we use requestAnimationFrame and switch tabs all tweens are paused and onComplete callbacs aren't fired at the proper time. If we use setTimeout gsap implementation the onComplete callbacks are invoked.

**Comment by jackdoyle** [comment]
Hm, I'm a bit confused, @apelev - are you running this in the browser? As I summarized above, setTimeout() won't solve this issue on modern browsers - they throttle setTimeout() along with requestAnimationFrame for hidden tabs so they're functionally equivalent. Do you have a minimal demo showing that setTimeout() would work but requestAnimationFrame() doesn't?

**Comment by djmisterjon** [comment]
you can have some demo here with ticks directors.
Demo for pixijs rendering engine, but logic fine for all kind of custom tikers
https://pixijs.io/examples/#/gsap3-interaction/gsap3-tick.js
![image](https://user-images.githubusercontent.com/24865815/111368702-93408080-866c-11eb-9bca-ec55cd88c77a.png)

**Comment by jackdoyle** [comment]
@djmisterjon were you trying to address what @apelev brought up? I'm still kinda lost - is the setTimeout() vs requestAnimationFrame() actually working differently in real browsers in any meaningful way? Does someone have a clear demo? According to my tests (which I did quite a while ago), browsers throttle setTimeout() too so there's no reason to expose a useRAF() method. All that'd do is add file size unnecessarily unless I'm misunderstanding something.

**Comment by apelev** [comment]
Hello again @jackdoyle. Didn't have time to setup a test project, so sorry for the late response. I've made a repo: 
https://github.com/apelev/gsap-raf-tests
To replicate our use case you need to open the given html in browser and switch to another tab. After 10 sec go back to the same tab and observe the logs. 
If we disable RAF and set lagSmoothing to 0 the callbacks have all been fired as observed in the logs(exactly what we need). If we don't do both of these things the second callbacks get triggered after we return to the tab. (in our use case, the animation begins upon returning to the tab, but all the time for the given animation has already passed so we have to skip it and just get to the final result that we need).

**Comment by jackdoyle** [comment]
Thanks for the minimal demo, @apelev ! I see exactly what you mean, but instead of adding useRAF() back to the ticker which would increase file size for everyone (not significantly, but I always try to avoid bloat where I can), I'd suggest using this helper function: 

```javascript
function tickGSAPWhileHidden(value) {
    if (value === false) {
        document.removeEventListener("visibilitychange", tickGSAPWhileHidden.fn);
        return clearInterval(tickGSAPWhileHidden.id);
    }
    const onChange = () => {
        clearInterval(tickGSAPWhileHidden.id);
        document.hidden && (tickGSAPWhileHidden.id = setInterval(gsap.ticker.tick, 500));
    };
    document.addEventListener("visibilitychange", onChange);
    tickGSAPWhileHidden.fn = onChange;
    onChange(); // in case the document is currently hidden.
}
tickGSAPWhileHidden(true);
gsap.ticker.lagSmoothing(0);
```
The reason this is even better than useRAF(false) is because it ONLY relies on setInterval() while the tab is hidden, but for normal updates it still uses requestAnimationFrame() which is always optimized for animation updates. In other words, useRAF(false) would force GSAP to always use setTimeout() instead which isn't always synchronized with screen repaints from what I understand. So the above solution gives us the best of both worlds: 

1. Conserves file size for the vast majority of users who don't need this functionality
2. Optimizes performance by using requestAnimationFrame() whenever possible
3. Still updates in hidden tabs (albeit at a reduced rate, like 2fps, but that's a limitation imposed by the browser)

Does that make sense? 

I've added it to the official "Helper Functions" in the docs too: https://greensock.com/docs/v3/HelperFunctions#hidden

**Comment by jkanchelov** [comment]
@jackdoyle this looks like it's going to work out perfectly. We are going to try it and leave feedback afterward, closing the issue with it. Thanks!
