### ISSUE TITLE
Suggestion: alternate tween method

### ISSUE THREAD

**Issue by h0merjam** [greensock/GSAP#438]
Hi,

Would you consider adding a `.tween()` method which takes an object containing `from` and `to` variables alongside the other tween options? eg.

```js
gsap.tween({
	from: {
		rotation: 0,
	},
	to: {
		rotation: 360,
	},
	duration: 1000,
});
```

This would make it possible to tween properties with any name and make the library simpler to use as drop-in replacement with other popular tweening libraries.

Thanks,
James

**Comment by ZachSaucier** [comment]
Hey James. You could easily create your own function that does this sort of thing in exactly the way that you need it. Something like this:

```
const tween = ({target, fromVars, toVars, duration, ...args}) => {
  if(typeof target === "undefined") return;

  if(fromVars) {
    if(toVars) {
      toVars.duration = duration / 1000;
      gsap.fromTo(target, fromVars, toVars);
    } else {
      fromVars.duration = duration / 1000;
      gsap.from(target, fromVars);
    }
  } else if(toVars) {
      toVars.duration = duration / 1000;
      gsap.to(target, toVars);
  }
}

// Usage
tween({
  target: "h1",
  duration: 3000,
  toVars: {
    color: "red"
  }
});
```
[Demo](https://codepen.io/GreenSock/pen/zYoeeeQ).

Does doing something like that serve your needs?

**Comment by ivodolenc** [comment]
@h0merjam this is a nice suggestion, I also like the idea. 👍

Maybe even simplified to something like this:

```js
gsap({
  from: {
    rotation: 0
  },
  to: {
    rotation: 360
  },
  duration: 1000
})
```

@ZachSaucier solution is a great alternative. This would be a helpful addition to the GSAP, so that user can import this from official package if needed.

**Comment by jackdoyle** [comment]
This isn't something I'd want to add because:

1. I'd rather not force everyone to pay a file size price for something that a tiny fraction of users might want
2. It bloats the API surface area and could lead to confusion when people see the standard .to()/.from()/.fromTo() calls that have always been a part of GSAP, and then they start also seeing other variants where there's this .tween({from:{}, to:{}}) syntax and wonder _"wait, which one is best? What's the 'right' way to do it?"_ 
3. Frankly, I'm not a fan of the suggested API. Feels overly verbose, and the plural "targets" vs singular "target" gets weird when you have either a multiple or single amount of actual targets. It's also more cumbersome to reuse the same object for particular effects, like a template (same vars object, different targets)
4. It's very simple to create the external function like Zach showed, so there's very little reason to force that into the core.

But thanks for the suggestion.
