### ISSUE TITLE
Feature request: time positioning with percentage

### ISSUE THREAD

**Issue by fcisio** [greensock/GSAP#444]
Hi, when creating dynamic animations, I often find myself doing this in order to position tweens in the timeline relative to the tweens, but also the total duration.

```js
const duration = 2.5

tl.to('.el', { x: 100 })
  .to('.el', { y: 200 }, `-=${duration * 0.25}`)
```

That way, I can ensure that changing the general duration won't have undesired side effects.

It would be really nice to introduce a behavior like this:

```js
.to('.el', { y: 200 }, '-=25%')
```

**Comment by jackdoyle** [comment]
Thanks for the suggestion, @fcisio ! I think it could be quite handy to have percentage-based values in the position parameter. Just to be clear, though, the percentage would be relative to the totalDuration() of the animation that's being added in, right? So let's say the entire timeline (containing many animations) is 10 seconds long, but then I do this: 

tl.to(..., {duration: 2...}, "-=50%");

It would be similar to "-=1" (one second overlap) because 50% of the duration (2) is 1. 

I'm not committing to this quite yet, but I've got an experimental version up at https://assets.codepen.io/16327/gsap-latest-beta.min.js that you can try out (it has this feature right now). I'm soliciting some input from VIPs in the community before we make any of this official. I'd appreciate it if you'd kick the tires a bit and let me know if it works the way you expected.

**Comment by fcisio** [comment]
Hey, glad to see this getting attention!
Would it be possible to create an actual codepen for this? I mainly use GSAP with React so it's tricky for me to test with the asset above.

Great point about "relative to which duration". I think that `totalDuration` would be the main use case, so the default, but it would be worth it to have a property to control if it should be relative to the preceding tween.
That could also be a new operator, ex: `+~50%`

- "-=50%" relative to preceding tween
- "50%" absolute / totalDuration

**Comment by jackdoyle** [comment]
> but it would be worth it to have a property to control if it should be relative to the preceding tween.
> That could also be a new operator, ex: `+~50%`

I think the most sensible option would be "<50%" because it's like an arrow pointing backward to the most recently-added animation. We already use that in the API, like "<" is the start of the previously-added animation, and "<0.5" would be 0.5 seconds after its start, etc. 

Here's a CodePen showing a very simple example: 
https://codepen.io/GreenSock/pen/413b602164d188db15619496442e4a29?editors=0010

Thoughts?

**Comment by fcisio** [comment]
It all looks good to me! 👌

**Comment by jackdoyle** [comment]
Included in the latest release.
