### ISSUE TITLE
Issue in throwUpdate method 

### ISSUE THREAD

**Issue by Tarkik3798** [greensock/GSAP#455]
There is an issue with _gsTransform while implement in react

**Comment by sadeghbarati** [comment]
https://greensock.com/gstransform/

https://greensock.com/3-release-notes

**Comment by jackdoyle** [comment]
Yep, @sadeghbarati  is exactly right - _gsTransform doesn't exist since GSAP 3 was released a few years ago. That's just for v2 and earlier.  It is now much simpler and more intuitive - you can simply use gsap.getProperty() to get those values. And they can include units now too (GSAP v2 and earlier couldn't accommodate units like vw or really anything except px but that's much improved in v3). 

I'd strongly recommend checking out the migration guide too at https://greensock.com/3-migration

If you've got any other questions, feel free to post in the forums at https://greensock.com/forums

**Comment by Tarkik3798** [comment]
But I already using V3 and If i am using _gsTransform then my spin is not rotating. I got undefined it.

**Comment by OSUblake** [comment]
> _gsTransform doesn't exist since GSAP 3 was released a few years ago. That's just for v2 and earlier. It is now much simpler and more intuitive - you can simply use gsap.getProperty() to get those values.

https://greensock.com/docs/v3/GSAP/gsap.getProperty()
