### ISSUE TITLE
how to set fps to every timeline or tween?

### ISSUE THREAD

**Issue by ks-stack** [greensock/GSAP#457]
not every animation need high fps, high fps use more cpu

**Comment by jackdoyle** [comment]
You can throttle the fps on the whole engine like:
```javascript
gsap.ticker.fps(30)
```

See https://greensock.com/docs/v3/GSAP/gsap.ticker

But it wouldn't make much sense to let each and every tween/timeline have its own independent fps. It could actually hurt performance due to all the conditional logic necessary on every tick for every tween/timeline.
