### ISSUE TITLE
Migration from Tweenmax to GSAP

### ISSUE THREAD

**Issue by whizzbbig** [greensock/GSAP#467]
Recently i am working on a project which use locomotive scroll and also a draggable image strip usng tweenmax
 since i am using gsap.min.js for locomotive scroll not for draggable image strip it causing errors as i am using tweenmax and in latest build it got migrated and i am too noob to do that i not even know a single thing in gsap always seems like a nightmare to me.

heres a repo btw please pull request migrate tween max to gsap scrolly.js is the file which contains tweenmax 

https://github.com/whizzbbig/superior-os/blob/main/README.md

video is too big to fit so i added in the README.md file
![Screenshot 2564-08-16 at 5 41 44 AM](https://user-images.githubusercontent.com/54703305/129496900-4f25edd0-227e-4500-8d26-4b06744f0993.png)

**Comment by jackdoyle** [comment]
Hi @whizzbbig

If your goal is to migrate an old v2 TweenMax project to the more modern GSAP 3 (which came out back in 2019) it should be pretty easy actually since most of the code is backwards compatible. There's a migration guide at https://greensock.com/3-migration

TweenMax was just a part of GSAP but it was simplified into a "gsap" object along with TweenLite, TimelineLite, and TimelineMax so everything is easier to understand and smaller file size. 

I think if you ask around and find people who have experience with GSAP, you'll discover that it's not at all a nightmare to use. Once you learn the basics, you'll feel like you have animation superpowers! That's probably why it's used on the majority of award-winning web sites and well over 10,000,000 sites total. 

If you have any GSAP-specific questions, feel free to post them along with a minimal demo at https://greensock.com/forums

We do not provide free migration services or custom consulting, nor can we support 3rd party libraries like LocomotiveScroll or Scrolly.js (never heard of that one). But we're happy to answer any GSAP-specific questions. 

If you want to hire someone to help you, feel free to post in the "Jobs & Freelance" forum here: https://greensock.com/forums/forum/15-jobs-freelance/

Good luck with your project!

**Comment by whizzbbig** [comment]
> Hi @whizzbbig
> 
> If your goal is to migrate an old v2 TweenMax project to the more modern GSAP 3 (which came out back in 2019) it should be pretty easy actually since most of the code is backwards compatible. There's a migration guide at https://greensock.com/3-migration
> 
> TweenMax was just a part of GSAP but it was simplified into a "gsap" object along with TweenLite, TimelineLite, and TimelineMax so everything is easier to understand and smaller file size.
> 
> I think if you ask around and find people who have experience with GSAP, you'll discover that it's not at all a nightmare to use. Once you learn the basics, you'll feel like you have animation superpowers! That's probably why it's used on the majority of award-winning web sites and well over 10,000,000 sites total.
> 
> If you have any GSAP-specific questions, feel free to post them along with a minimal demo at https://greensock.com/forums
> 
> We do not provide free migration services or custom consulting, nor can we support 3rd party libraries like LocomotiveScroll or Scrolly.js (never heard of that one). But we're happy to answer any GSAP-specific questions.
> 
> If you want to hire someone to help you, feel free to post in the "Jobs & Freelance" forum here: https://greensock.com/forums/forum/15-jobs-freelance/
> 
> Good luck with your project!

Thanks sir, for your response gsap cannot be a nightmare and soon i'll be able to feel ez with it :)
