### ISSUE TITLE
Killing a timeline that uses ScrollTrigger does not kill the associated animation

### ISSUE THREAD

**Issue by dan2kx** [greensock/GSAP#471]
i have created a simple reproduction here: https://codesandbox.io/s/wonderful-sun-bjb42

Basically, i am creating a timeline on one page within a useEffect and killing the timeline in the unmount of that effect. 

Clicking on the link to go to the second page should cause the unmount to trigger and kill the timeline (which it does), but the ScrollTrigger animations are still operating on the new page. You can see this in the console logs, the animation is still firing the onUpdate event.

I've discovered that i can loop through the tweens using the `timeline.getChildren()` method and kill each manually, but i would expect the default behavior here should be to kill all of the scrollTrigger animations along with the timeline to prevent orphaned animations?

**Comment by OSUblake** [comment]
ScrollTriggers should be declared inside the timeline. 
```js
const animation = gsap.timeline({
  scrollTrigger:  {}
})

...
animation.scrollTrigger.kill();
```

Check out the common mistakes page.
https://greensock.com/st-mistakes/#st-in-tl

```
A very common mistake is applying ScrollTrigger to a bunch of tweens inside a timeline. This doesn’t make much sense because both the timeline and the ScrollTrigger would try to control the tweens' playhead. 

It's best to apply a ScrollTrigger to either a standalone tween or to a parent timeline.
```

**Comment by jackdoyle** [comment]
Due to someone else being misled by the comment above, Blake didn't mean that all ScrollTriggers must be associated with a timeline - he was simply saying that if you're going to use a ScrollTrigger with a timeline (sequenced animation), you should NOT define multiple ScrollTriggers on individual child tweens inside that timeline - you should just define one ScrollTrigger on that timeline. 

You can definitely have a ScrollTrigger on an individual tween that's **not** inside a timeline. That's very common in fact.
