### ISSUE TITLE
Uncaught ReferenceError: CSSPlugin is not defined

### ISSUE THREAD

**Issue by nazifa22** [greensock/GSAP#475]
I have used the transform effect on footer, but it has started shaking when I scroll to that section! Is there any solution where I can get rid of that unwanted shaking!
I am attaching my footer code below.

`
import $ from "jquery";
import gsap from "gsap";

var $footer       	= $('.footer');
var $scrollup   	= $footer.find('.scrollup');
var dHeight 		= null;
var wHeight			= null;

if($footer.length){
	$footer.css({'height':wHeight});

    $scrollup.find('.button').on('click', function(){
		gsap.to(window, 1, {scrollTo: {y: 0 , ease: 'Power3.easeOut'}});
	});

	wHeight = window.innerHeight;
	dHeight = $(document).height();

	$(window).on('resize', onResize);
	
	onResize();

}

function onResize(){
	wHeight = window.innerHeight;
	dHeight = $(document).height();

	$footer.css({'height':window.innerHeight});
}
`

Thanks for the help in advance :)

**Comment by jackdoyle** [comment]
Hi @nazifa22

This kind of question is perfect for the forums at https://greensock.com/forums - just make sure you include a minimal demo (like a CodePen) because it's very difficult to troubleshoot blind. This doesn't belong as a Github issue. 

I also didn't understand the title of your issue - are you saying that you're getting an Uncaught ReferenceError? 

My guess is that the problem is simply that you're using a power3.out ease which goes much slower at the end, but most browsers only scroll by whole pixels, thus the browser "snaps" to those whole pixels. For example, GSAP may be setting the value to 0.65 but that snaps to 1. Then GSAP sets it to 0.84 and again, it snaps to 1, when it eventually crosses the threshold to the next number, you see it jump 1 pixel, making it appear "jittery". That's not a GSAP problem - it's just how browsers work. You could try using a shorter duration or a different ease that isn't so heavily weighted at the end so that the movement isn't so slow.
