### ISSUE TITLE
Timeline & Labels

### ISSUE THREAD

**Issue by zangab** [greensock/GSAP#486]
### Question
I plan to create an animation where something (a menu) fades in from top on click, and fades out to bottom on another click. So the animation is not reversed, but repeats itself. If closed, enter from top, if open, leave to bottom.
Can i accomplish this with ONE timeline?
Or do i have to setup multiple tweens / timelines for it?

Currently, I just reverse the timeline cause it's not working.
I tried using 1 timeline with labels and then play them via `.tweenFromTo('top', 'top-end').play()` and `.tweenFromTo('bottom-start', 'bottom-end').play()`. However, if I initialize the timeline, it seems not to be at 0, but at the bottom-start label. The timeline is paused on init.
Is there any example for something like this?

**Comment by jackdoyle** [comment]
Absolutely, there are many ways you could do that, including with a single timeline but I'm curious why you want to do it that way. Like...is there something important to you about having it in a timeline? 

What do you mean by "if I initialize the timeline it seems not to be at 0"? Can you please provide a minimal demo? That'd significantly increase your chances of getting a good answer. 

A question like this is definitely a good fit for the forums at https://greensock.com/forums (Github issues are more for bug reports). And again, a minimal demo, like a simple CodePen, will REALLY help.

**Comment by jackdoyle** [comment]
That's because .fromTo() animations always have immediateRender: true by default since that's almost always what people find most intuitive. However, you have MULTIPLE .fromTo() tweens of the same element in the timeline, thus the last one is what controls the initial property because that's the last one that renders immediately. It's a simple fix - just set immediateRender: false on that one. 

Also, I'd strongly recommend using yPercent: 100 instead of translateY: "100%" and make sure you set all transforms via GSAP for maximum speed and accuracy. See https://greensock.com/mistakes#transforms

Here's a fixed CodePen: https://codepen.io/GreenSock/pen/VwMNGBq?editors=0010

But you really don't need to use a timeline - here's a simplified version that doesn't use a timeline: 
https://codepen.io/GreenSock/pen/yLzrxRb?editors=0010

Happy tweening!

**Comment by zangab** [comment]
i see.
thank you sir, appreciate
🙇 👍
