### ISSUE TITLE
No setting but 50% more offset

### ISSUE THREAD

**Issue by WorldToCode** [greensock/GSAP#487]
I'm not sure if I'm using it wrong
![image](https://user-images.githubusercontent.com/65691266/149698232-504479c7-64d6-4bb2-9a1e-4b906b76e042.png)
![image](https://user-images.githubusercontent.com/65691266/149698456-08e2c38e-25e6-4fc0-9174-c035d99e7357.png)
I can only use negative offset to solve the problem

**Comment by WorldToCode** [comment]
This is css
![image](https://user-images.githubusercontent.com/65691266/149699858-537f3719-5308-457e-8ed3-a07cf5b68783.png)

**Comment by jackdoyle** [comment]
Without seeing a minimal demo, I'll make a guess that this is one of the common mistakes people make of not setting all the transforms through GSAP. https://greensock.com/mistakes#transforms

GSAP lets you use both x/y and xPercent/yPercent which is quite useful because, for example, you could center something with xPercent: -50, yPercent: -50 and then move x/y such that its center is at that spot. The important thing here is that there's BOTH an "x" and "xPercent" that you can use...

When GSAP parses the current transforms, the browser reports them in a matrix() or matrix3d() which are always pixel-based (no percentages). GSAP must break down into the individual components and for translation, it must decide where to put x/y or xPercent/yPercent. The only time it will put it in xPercent/yPercent instead of x/y is when it's exactly -50% because that's so common, so it was our attempt at making GSAP intuitive. 

So you really shouldn't ever set x: "50%". Instead, you'd do xPercent: 50. And if you're setting things in CSS, you should also do it in GSAP just so that it parses the values exactly as you desire because matrix values can be very ambiguous. So to set everything to 0, it'd be: 

gsap.set(dom1, {x: 0, xPercent: 0, y: 0, yPercent: 0});

If you still need some help, please post your question in the GSAP forums along with a minimal demo and we'd be happy to help with any GSAP-specific questions. 

Happy tweening!

**Comment by WorldToCode** [comment]
Why can't I find the attribute value on the official website, for example yPercent

**Comment by OSUblake** [comment]
It's documented in the [CSSPlugin docs](https://greensock.com/docs/v3/GSAP/CorePlugins/CSSPlugin).

> To do percentage-based translation use xPercent and yPercent instead of x or y which are typically pixel based. Why does GSAP have special properties just for percentage-based translation? Because it allows you to COMBINE them to accomplish useful tasks, like perhaps you want to build your own “world” where everything has its origin in the very center of the world and then you move things in a px-based fashion from there - you could set xPercent and yPercent to -50 and position: "absolute" so that everything starts with their centers in the same spot, and then use x and y to move them from there. If you set x or y to a percent-based value like "50%", GSAP will recognize that and funnel that value to xPercent or yPercent appropriately as a convenience.

**Comment by WorldToCode** [comment]
thank you!
