### ISSUE TITLE
Scroll trigger tilt

### ISSUE THREAD

**Issue by karlafalcao** [greensock/GSAP#492]
Scroll trigger demo is showing white a box when triggering scroll. Pls, see video attached

https://user-images.githubusercontent.com/641596/154412194-e3240de9-8d9f-45a0-9b2f-2a97a6f3efd6.mov

.

**Comment by jackdoyle** [comment]
Thanks for the video! 

That's not a box - it's the background showing for a brief moment which is due to the fact that browser run scrolling updates on a DIFFERENT THREAD, so it's out-of-sync with the main JavaScript thread. So when you scroll quickly like that, the browser actually renders the page as if that element isn't pinned yet (so you scrolled right past it) and then it executes the JavaScript thread which says "hey, buddy, that thing needs to be pinned!" and it renders it appropriately. So that flash is the time between the threads executing. 

It's not a bug. It's a logical impossibility to work around as far as I know, unless you move ALL of your scrolling to the JS thread which typically means scroll-jacking (like a smooth scrolling library). 

You can set anticipatePin: 1 (or some number) to tell ScrollTrigger to try to anticipate when that pinning should occur ahead of time and essentially pin it a bit early. In other words, it'll watch the velocity and try to predict "oh, at this speed they're gonna hit the pin on the next frame so go ahead and pin it NOW to try to avoid that jump".
