### ISSUE TITLE
ScrollTrigger scrubbing animations cause other scrubbing animations to jump.

### ISSUE THREAD

**Issue by travisrobie** [greensock/GSAP#497]
Scrubbing animations that have different triggers and targets, but occur at roughly the same time can cause one target to 'jump'.
This only happens in one direction, depending on what order the timelines are initialized.

See https://codepen.io/trobie/pen/OJOdGxQ

Scroll slowly and you will see the expanding white box 'jump' to its end state each time the other animation triggers onEnter or onLeave. It does not seem to affect older versions of GSAP / ScrollTrigger. 
This does not happen with 3.7.0

**Comment by jackdoyle** [comment]
That's because you've got preventOverlaps: true which was added in version 3.8. You're using it incorrectly there and it's causing a conflict. When you enable that feature, it basically means "when I start, find all trailing ScrollTrigger-based animations and force them to completion". This is super handy in many cases but you're intentionally overlapping your ScrollTriggers, thus it's improper to use this setting here. 

So when your box1 gets triggered, it finds the trailing ScrollTrigger animation and forces it to completion...but then as you continue scrolling the scrub kicks in and sets it back to the proper value. Again, the problem here is that you overlapped them intentionally but you're telling ScrollTrigger to FORCE trailing ones to completion in order to PREVENT overlaps. 

See https://greensock.com/3-8 for more info about that setting.

An easy fix for you is to either remove preventOverlaps: true from you ScrollTrigger -OR- you could give it a specific name if you want to target the behavior so that it only affects ones with a matching name. 

I think I'll add some extra logic to ONLY affect ScrollTriggers whose start/end values aren't supposed to overlap. You can preview that upcoming release at https://assets.codepen.io/16327/ScrollTrigger.min.js

Does that clear things up?

**Comment by travisrobie** [comment]
Thank you very much for the detailed explanation, and sorry for my 'fake bug' report.
I did not know that the older version of GSAP didn't have preventOverlaps!
Could not figure out why the jumping was happening in my project, but not in my pen.
