### ISSUE TITLE
When I used Pixi Plugin and set a scale animation to a sprite, size is worry

### ISSUE THREAD

**Issue by Elon-Yan** [greensock/GSAP#498]
code:
const picture = PIXI.Sprite.from('...')
picture.width = 40
picture.height = 60
picture.x = 90
picture.y = 90

gsap.to(picture, {
    keyframes: {
        '0%': {
            pixi: {
                scale: 1,
            }
            
        },
        '50%': {
            pixi: {
                scale: 1.2,
            }
            
        },
        '100%': {
            pixi: {
                scale: 1,
            }
        },
    },
    duration: 2,
    repeat: -1
})

**Comment by jackdoyle** [comment]
I don't quite understand your question. Can you please clarify? Do you have a minimal demo, like a CodePen that shows the issue? 

Also, you could simply animate to scale: 1.2 and set yoyo: true to get a similar effect with less code (no need for keyframes).

**Comment by Elon-Yan** [comment]
[demo](https://jsfiddle.net/jbogut35/1/)

I set this picture width\height for 100, and scale from 1 to 1.2, so I think the width\height is 100~120

**Comment by OSUblake** [comment]
I'm not sure what you're asking here, but width and height in PixiJS change the scale and vise versa. That has nothing to do with GSAP, and is just how PixiJS works. Try logging out the scale before creating your animation.

```js
picture.width = 100
picture.height = 100

app1.stage.addChild(picture)

console.log(picture.scale.x) // 0.1893939393939394
```

If you want to animate to a width/height of 120, then you should animate the width and height properties instead of scale.
