### ISSUE TITLE
[bug] keyframes and timeScale with high value

### ISSUE THREAD

**Issue by minimit** [greensock/GSAP#500]
Hello again, I've a problem using keyframes together with a big `gsap.globalTimeline.timeScale`.

You can see the bug here https://codepen.io/minimit/pen/qBxEJVB , just mouse over the red box.

With this timeScale the animation stops on the first keyframe instead of stopping on the last keyframe.

Note that if you use a smaller value `gsap.globalTimeline.timeScale(10);` the animation works but with higher values the bug appears.

**Comment by jackdoyle** [comment]
Great catch, @minimit - thanks for reporting that. It should be fixed in the next release which you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js

It **only** affects Array-based keyframes when you set a duration on the tween.

In the meantime, you could resolve it by adding .timeline.duration() at the end of the tween(s) like: 
https://codepen.io/GreenSock/pen/wvyaBwb?editors=0010
