### ISSUE TITLE
GSAP 3.11.1 trigger weird scroll behaviour for ScrollerProxy

### ISSUE THREAD

**Issue by reksaandhika** [greensock/GSAP#515]
I try to update GSAP to the newest version, because want to using new features GSAP match media, but end up triggering bug.
So this happen for ScrollerProxy, I'm using Locomotive Scroll for the scroller, `ScrollTrigger.refresh()` make the scroll weird, I can't scroll smoothly when refresh code fired.

This bug happen only on newest version (3.11.1), I tried same code on older GSAP version is normal (3.11.0)

Here is the example Codepen:
I try ScrollTrigger.refresh() on `setInterval` 3s, try scrolling up and down.

GSAP 3.11.1 (Bug)
[Codepen](https://codepen.io/reksaandhika/pen/PoebqyO)

GSAP 3.11.0 (Normal)
[Codepen](https://codepen.io/reksaandhika/pen/bGMBVNx?editors=0010)

Thank you.

**Comment by jackdoyle** [comment]
Thanks for reporting this, @reksaandhika . We'll look into it and get back to you.

**Comment by reksaandhika** [comment]
No problem @jackdoyle, happy to contribute to making GSAP better.

Hope this can fix soon, I love using new matchMedia, and I already refactor my project code with that, will lot of work again to reverse to old version.

**Comment by jackdoyle** [comment]
Yeah, the problem isn't actually ScrollTrigger/GSAP - it's because LocomotiveScroll's API changed in v 4.x and you need to change this:
```javascript
// old
locoScroll.scrollTo(value, 0, 0);
// new
locoScroll.scrollTo(value, {duration: 0, disableLerp: true});
```
https://codepen.io/GreenSock/pen/rNvyYLR?editors=1010

In order to work around an edge case in ScrollTrigger, we needed to make sure the scroller's scroll position is reset to 0 while doing refresh() calculations and then we return it to the pre-refresh() value (invisible to the user) but LocomotiveScroll was not handling that properly (it was acting like an interruption, like it was trying to lerp or something).  

I updated the demo in our docs too. 

Better?

**Comment by reksaandhika** [comment]
Hey Jack, great solution for LocomotiveScroll, thanks for that, is it a production-ready solution or a temporary solution and better wait for update the next update GSAP?

I don't understand technically and what you guys trying to achieve with new update on ScrollTrigger that affect scroller on ScrollTrigger.refresh().

It's happened with multiple 3rd party scroller, I have tested it, and here's what I got:

Pass test:
✅ [Smooth Scrollbar](https://github.com/idiotWu/smooth-scrollbar) (maybe because the ScrollTrigger.refresh() not bind on scroller?)

Failed test:
❌ [Locomotive Scroll](https://github.com/locomotivemtl/locomotive-scroll/) (example: [codepen](https://codepen.io/reksaandhika/pen/PoebqyO)) - Just cracked the solution
❌ [ASScroll](https://github.com/ashthornton/asscroll) (example: [codepen](https://codepen.io/reksaandhika/pen/NWMpYLB?editors=0010))

**Comment by jackdoyle** [comment]
Unfortunately we just can't offer support for 3rd party libraries - it looks like LocomotiveScroll has an issue where if you set the scroll value, it doesn't actually report it accurately for a while. You can verify that pretty easily (set it in the scrollTop() setter and then try reading it back right away and you'll see). Maybe ASScroll has a similar issue(?)

In short, when ScrollTrigger does a refresh() to calculate all the start/end positions, it has to temporarily put the scroll position back to 0 so that nested things aren't contaminated. There are some edge cases where if you had something pinned, scrolled into that area and did a refresh(), things could be thrown off if we don't reset the scroll to 0 to do all the measurements. So the updated ScrollTrigger is actually fixing some things. I realize your experience seems the opposite, but I'd argue it's simply exposing flaws in some of the 3rd party smooth scrolling libraries. 

You do know that GreenSock has its own smooth scrolling tool, right? https://greensock.com/scrollsmoother

Obviously I'd recommend using that.

**Comment by reksaandhika** [comment]
Thanks for explaining how ScrollTrigger refresh works, so I assume you are sure the update for better ScrollTrigger and not mistakenly create a bug.

I do know ScrollSmoother from GreenSock, but I don't like the easing.

Well I think I have no choice, not just about scroller,  since I update 3.11.1 my animation is sometimes jittering than the previous version, I think using matchMedia and trade for all this cause is not worth it, guess I will go back to prev version :(

**Comment by jackdoyle** [comment]
I'm super curious about this "jittering" comment. Can you please provide a minimal demo illustrating that? 

As for the easing, did you know you can give the ScrollSmoother any ease you want? It defaults to "power3.out".

**Comment by reksaandhika** [comment]
For the jittering, it happens when you have a complete website with full animation, I find out it's pretty hard to reproduce the jitter on a minimal demo.

I know about easing on ScrollSmoother, but feels different with scroll jacking, also ScrollSmoother sometime lag on scroll and fps not stable (fps drop under 60fps), that's why I prefer scroll jacking even so many things to sacrifice.

**Comment by reksaandhika** [comment]
@jackdoyle I just found the jitter issue on GSAP 3.11.1 version,
Once I reload my browser, and before the site loaded, I go to another tab, then go back to my site, the animation is firing twice.
This only happen on 3.11.1 version, 3.11.0 is fine.

Sadly I can't publish my WIP project, and I have tried to reproduce on demo with codepen, but that doesn't trigger the jitter.

**Comment by jackdoyle** [comment]
@reksaandhika Hm, can you verify that it's not an issue in the upcoming release?: 

GSAP: https://assets.codepen.io/16327/gsap-latest-beta.min.js
ScrollTrigger: https://assets.codepen.io/16327/ScrollTrigger.min.js

**Comment by reksaandhika** [comment]
@jackdoyle Will do that, I think the jitter is happening for "transform" property, maybe because on 3.11.1 the transform using different new one, i check gsap using new CSS standalone transform like "translate: none;", "rotate: none;", "scale: none;"

**Comment by jackdoyle** [comment]
Nah, those are there purely to prevent contamination. They're totally unused by GSAP. All transforms are merged into the single "transform" property. 

We're on the verge of pushing 3.11.2 live, so the sooner you can test that and get back to us, the better :)

**Comment by reksaandhika** [comment]
@jackdoyle okay understandable.
Anyway Jack, how to test your files in webpack environment?

I need to use ES Modules (import method)

**Comment by reksaandhika** [comment]
I copy & paste your files to gsap/dist on node_modules
and I'm using `import gsap from 'gsap/dist/gsap.min.js';` `import ScrollTrigger from 'gsap/dist/ScrollTrigger.min.js';`
am I right?

The jitter is not there anymore, but the ScrollTrigger is not running (I have no error in the console).

**Comment by jackdoyle** [comment]
You can just update to 3.11.2 which we just pushed out through all official channels (though the CDNs may still take a little while to update).

**Comment by reksaandhika** [comment]
Thanks, Jack for the update, I have tested the 3.11.2, and the jittering for transform animation is solved (but sometimes still triggers, but it's just rarer now), I will close the issue (if someone looking for solution for ScrollerProxy, you can see second Jack reply).

Also drawSVG with gsap.from is firing twice (on MacBook, I see no issue on Windows - PC), but that's for another issue maybe, I will provide demo if I can.

Thanks @jackdoyle for the help and for being so active, it means so much to me!

**Comment by jackdoyle** [comment]
No problem, @reksaandhika 

As for the .from() firing twice, I need to know exactly what you mean by "firing twice" because it's actually normal for it to set the initial value twice because immediateRender is true by default for from() and fromTo() tweens (so it renders right away) but then it must do it again when the animation actually starts for the first time because it's possible that other code (maybe another tween) could have altered it since then. Imagine creating a tween that you then put into a timeline so that it's scheduled to begin much later. 

It should make absolutely no difference if it's on a Mac or Windows machine. GSAP works identically either way. If you think there's a problem, please create a minimal demo and post in the forums at https://greensock.com/forums and we'd be happy to take a peek.

**Comment by reksaandhika** [comment]
For "twice" issue, It's fixed with timeline instead using gsap.from, it's because my animation have "delay" property and the code sometime won't immediately run the "from" statement but somehow fixed with timeline.

But it's only happening on >3.11.0 version, on 3.10.4 the delay is no issue even I'm using standalone "gsap" not timeline. @jackdoyle

**Comment by jackdoyle** [comment]
@reksaandhika I didn't quite follow your explanation there - it would be EXTREMELY helpful if you could provide a minimal demo. Just a simple CodePen that illustrates the issue (NOT your whole project). A few colored <div> elements is fine. 

And yes, in 3.11.0, we made some sweeping changes internally in order to accommodate the very exciting matchMedia() and context() and revert() features. This required updates to the way .from() and .fromTo() work internally because it must record the pre-animated state (inline styles) in order to be able to cleanly revert() them. 

I'm very curious about seeing that demo. :)

**Comment by reksaandhika** [comment]
There are many things I want to let you know >3.11.0 bug (so I stay on gsap 3.10.4 version for my projects).
I find some bug is hard to reproduce with a minimal demo, but I will find out and let you know when I have the demo.

When I have more time I will try to reproduce it with a minimal demo.
