### ISSUE TITLE
gsap.from animations flash end state of element since 3.11.0

### ISSUE THREAD

**Issue by gianpesto** [greensock/GSAP#522]
Since 3.11.0 if you have a couple of `.from` animations with label, that happen all at the same time very often flash the end-state of the element for a fraction of a second.

Upon debugging i saw that gsap is now setting `translate`, `scale` and `rotate` on elements and set them all to `none`.
When the animation triggers all of the above properties seem to be removed and then re-applied. 
Also the animated property with its starting value is removed and then reapplied. This is where the browser seems to repaint and flashes the element in a wrong state.

This flash doesn't happen all of the time and shows up very inconsistently, but happens in all of the major browsers (i tested on mac osx)

**Comment by jackdoyle** [comment]
Thanks for letting us know, @gianpesto. Sorry about the hassle.

I believe this is already resolved in the next release which you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js

Better? 

By the way, it has nothing to do with the scale/translate/rotate inline properties. Those are simply there to ensure that transforms aren't contaminated with those newer properties (GSAP always uses the universally compatible "transform" property). 

The issue was related to the new revert() functionality in v 3.11 and some of the cleanup necessary. Again, I believe it is already resolved but I'd appreciate it if you could confirm that the beta file resolves things for you. Thanks!

**Comment by jackdoyle** [comment]
Oh! I think this is just a misunderstanding and has nothing to do with GSAP or a bug...

When the browser loads a page, it goes top-to-bottom, and it renders the markup and then once that's fully loaded/parsed, THEN it executes JavaScript. So my guess is that you're experiencing the same thing that's behind the "flash of unstyled content" which you can read about at https://greensock.com/fouc

So basically your page renders for a very brief moment (depending on various browser and network related factors) and then the gsap.from() stuff executes, rendering things in their "from" state. The reason it looks intermittent to you (assuming I understand correctly) is because if the CPU isn't too busy and/or if the files load quickly enough, the browser may actually execute the JavaScript fast enough to where a tick doesn't elapse between initial render of the DOM and the initial execution of the JavaScript. 

You can get around that by just setting the initial state in the CSS, like maybe you set your container <div> to have visibility: hidden, and then the very first line of your JavaScript you do gsap.set(".container", {autoAlpha: 1}) or something like that. 

Does that clear things up?

**Comment by gianpesto** [comment]
Hey Jack, thanks for getting back. No, i don't mean the fuoc on page-load. the bug i am experiencing happens way after pageload when the initial from state is already applied to the element.

 I could narrow it down that this happens only when multiple from animations happen at the same time (i.e. with a label), and also very inconsistently (as i mentioned you might see this 1 out of 10 times.

i tracked down at what point this little flash is visible:
let's assume you want an element to fade in at the same time when some other element does something fancy.

- gsap sets the initial state (opacity: 0)
- when the element is supposed to fade in, gsap removes that inline property (can't tell the reason why) and re-sets it and starts animating it. This is the frame where for some reason the elements might flash it's state without inline-styles

**Comment by jackdoyle** [comment]
Ah yes, I see what you mean and I'm looking into it. In the meantime, I'm pretty sure that setting lazy: false solves it. Stand by for more details as I dig in. The glitch only happens if the playhead lands DIRECTLY on top of the starting position of a from() tween that doesn't have lazy: false.

**Comment by jackdoyle** [comment]
I figured it out and it should be resolved in the next release which you can preview at: 
https://assets.codepen.io/16327/gsap-latest-beta.min.js

Better?

**Comment by jackdoyle** [comment]
Should be fixed in 3.11.4
