### ISSUE TITLE
React + GSAP 3; Animation not working after deployment

### ISSUE THREAD

**Issue by blessme247** [greensock/GSAP#523]
I have a react project initiated with create react app. I added a homepage reveal animation with GSAP, the animation works in my development server(localhost) but does not work after deployment. I have read a similar issue (#285) and I followed some of the suggestions after which the animation still does not work in production.

I have attached 2 screenshots of my code snippets and 1 for my package.json file (which shows the version of my react and gsap). I hope to get feedbacks on what I'm doing wrong.

Thank You.

![Screenshot (446)](https://user-images.githubusercontent.com/67491400/209972349-1232fe58-c2e3-4060-88bc-b1ea20bd1368.png)
![Screenshot (447)](https://user-images.githubusercontent.com/67491400/209972403-72c5ea30-a4bc-43f2-86f2-963633b41244.png)
![Screenshot (448)](https://user-images.githubusercontent.com/67491400/209972726-4fd0991b-4ca3-4c61-98cb-7d115e759c86.png)

**Comment by jackdoyle** [comment]
Hi @blessme247 

It's almost impossible to troubleshoot by just looking at an excerpt of the code - can you please provide a CodeSandbox or Stackblitz that clearly demonstrates the issue? GSAP works great with React and we haven't heard of anyone else having issues like what you described - it really sounds like an issue with tree shaking on your end. 

I'd strongly recommend using gsap.context() and doing proper cleanup because React can be very picky. Like in React 18+, it calls the useEffect() TWICE in strict mode which can lead to creating conflicting/duplicate tweens/ScrollTriggers. But gsap.context() makes it super easy to do cleanup/reverting. 

Please read this article: 
https://greensock.com/react

I wonder if just wrapping your stuff in a gsap.context() will resolve things for you. If not, please provide that minimal demo in CodeSandbox/StackBlitz and we'll take a peek. Do NOT include your whole project - just a few colored <div> elements should be fine. The simpler the better.

**Comment by blessme247** [comment]
Hi @jackdoyle thank you for your response, I went through the article and I found out that I wasn’t wrapping my animation around the uselayout effect and the GSAP.context(). After following the steps, I have been able to fix the issue and my animation works fine now. The issue can be closed now.
