### ISSUE TITLE
Not compatible with worker environments

### ISSUE THREAD

**Issue by frandiox** [greensock/GSAP#524]
Hi! It seems that GSAP is not compatible with environments like Cloudflare Workers or [Shopify's Oxygen](https://github.com/Shopify/hydrogen/discussions/494).
I believe the reason (or, at least, the first one I've found) is that we can't call `setTimeout` outside of a request cycle in these environments, and GSAP is calling it directly during import inside the `registerPlugin` function.

Would it be possible to delay [this call to `wake()`](https://github.com/greensock/GSAP/blob/b357b544eda95770bd93c732549670c155d7d154/src/gsap-core.js#L666) somehow? Or change it to `windowExists() && wake()`? I'm not familiar with the code base so I don't know if that would break anything.

To reproduce this issue, you can run the following code with [Wrangler](https://www.npmjs.com/package/@cloudflare/wrangler):

```js
import gsap from 'gsap';

export default {
  fetch() {
    console.log(gsap);
    return new Response('ok');
  }
}
```

**Comment by jackdoyle** [comment]
Hi @frandiox 

It sounds like the proper solution is to move your gsap.registerPlugin() into an area in your code where it's "legal" to refer to setTimout() or whatever. It's the same thing for SSR stuff. Or use conditional logic, like: 

if (typeof window !== "undefined" && typeof(setTimeout) !== "undefined") {
  gsap.registerPlugin(...);
}

The reason it wouldn't be appropriate for us to change things internally like you suggested is that the registerPlugin() actually NEEDS to be able to reference things like document, window, etc. in order to do its job. 

Can you just make sure that you register the plugin when the proper methods/objects are available?

**Comment by frandiox** [comment]
@jackdoyle Thanks for checking this!

>It sounds like the proper solution is to move your gsap.registerPlugin() into an area in your code where it's "legal" to refer to setTimout() or whatever

The thing is, I'm not calling `registerPlugin` myself. It is called automatically by GSAP [at import time in `index.js`](https://github.com/greensock/GSAP/blob/master/esm/index.js#L3). I tried to import from `/gsap-core.js` and `/CSSPlugin.js` directly to avoid that but it turns out there's also [another call in the outer scope of `/CSSPlugin.js`](https://github.com/greensock/GSAP/blob/master/esm/CSSPlugin.js#L1545).

Perhaps the way would be using dynamic imports inside a `React.lazy` or similar, although I think this depends on the way the compiler bundles the code for a worker. In any case, thanks for the input!

**Comment by jackdoyle** [comment]
Yeah, that's necessary for CSSPlugin to get merged into the core and excluded from tree shaking (it's the one plugin that does this because CSS is so essential but we wanted to break it out as a separate JS file not only for development convenience but also to make it possible for hardcore devs who don't need CSSPlugin to save the kb and only use the core.)

Sorry, I have zero experience with Wrangler (never even heard of it) and it looks like I'd have to do a bunch of configuration, set up a Cloudflare account, etc. just to run a test, right? 

This sure sounds like maybe a configuration issue. It's very odd to me that a runtime JS file like GSAP would be expected to execute in an environment where something as fundamental as setTimeout() isn't available. Or maybe I'm misunderstanding. Do you think you could configure your environment so that it'd only load GSAP when setTimeout/window/document are available?

**Comment by mimikn** [comment]
I stumbled apon the same issue after some tests, so let met try to summarize some stuff.  
Cloudflare Workers does execute your code on the Edge (CDN) in isolated environment if you request a specific URL (you can find more infos [here](https://developers.cloudflare.com/workers/learning/how-workers-works/)).

My case was to test some hybrid rendering (incremental static regeneration) via Nuxt3, which the goal is to be able to generate static pages on demand directly on the Edge network. Thus, similarly to an SSR (Server Side Rendering) environement, Nuxt (via [Nitro](https://nitro.unjs.io/)) will bundle your application to be able to do that.  

On a classical node server environment, if you properly coded your stuff (calling `gsap()` only on the client side), your bundled code will still work with the imported gsap library on the server side, because `setTimeout()` does exists under Node.js and so the calling of `registerPlugin()` at the import of the library won't throw an error.  

But on cloudlflare workers, `setTimeout()` does exists, but will throw an error if called outside the handling of a request.

```js
function dirtySleep(time) {
  return setTimeout(() => {}, time);
}

// dirtySleep(200); => will throw an error

export default {
  async fetch(request) {
    dirtySleep(200); // => will work
    return new Response('Hello World!');
  },
};
```

The error that is thrown : Uncaught (in response) Error: Some functionality, such as asynchronous I/O, timeouts, and generating random values, can only be performed while handling a request.

So, since importing the gsap library will execute the `gsap.registerPlugin(CSSPlugin)` at runtime, it will throw an error.

I tried to share my example above in Cloudflare's (limited) playground, but for whatever reason, it's not working, but you may test it and copy/paste it into their playground directly : https://cloudflareworkers.com/

Hope this can help if something is doable about it.

**Comment by jackdoyle** [comment]
I don't have time to dig into this right now, but do you know of a reliable way to sense if the environment is "safe" to register in? Requirements: things like window, document, and setTimeout() must exist and be functional. I'm just wondering if there's a way to add a little conditional logic to work around this.

**Comment by jackdoyle** [comment]
I believe 3.11.5 may resolve this. If not, just let us know.
