### ISSUE TITLE
weird behavior with seek timeline

### ISSUE THREAD

**Issue by djmisterjon** [greensock/GSAP#528]
hi , why i get those gap or freeze when we play reverse a timeline with seek.

here demo, move mouse forward is fine, but not backward !
https://codesandbox.io/s/awesome-firefly-bchgvg?file=/src/index.js

---
here behavior
![ae3fa3auhhgva](https://user-images.githubusercontent.com/24865815/222423746-3bf56e67-a701-4b86-88a6-d10f26261e26.gif)

**Comment by jackdoyle** [comment]
That's because you're creating overlapping/conflicting tweens that are both trying to control the same properties of the same object simultaneously in two different directions. Both are 1 second long, but you added the 2nd one at a time of 0.7 seconds on the parent timeline, thus they overlap by 0.3 seconds. 

I'm not really sure what you're trying to do there, but your code could be simplified quite a bit. Did you know you can animate multiple properties with one tween? And you don't need to create individual tweens and add() them to a timeline - you can just use the timeline's .to() method, for example. I also wonder if you meant to use ease: "none" on those animations. 

If you need some help, the best thing to do is to post in the forums at https://greensock.com/forums and include a minimal demo. And thanks for providing that minimal demo CodeSandbox! It really helps identify issues quickly. In your case, it's just a logic problem in your code. 

Does that clear things up?

**Comment by djmisterjon** [comment]
>  And you don't need to create individual tweens and add() them to a timeline - you can just use the timeline's .to() method, for example. I also wonder if you meant to use ease: "none" on those animations.

Yes, maybe for the purpose of the example, I probably gave you poor code.
 
The code base looks like this. 
What you can see here is that I create a timeline with preset data.
 ![image](https://user-images.githubusercontent.com/24865815/222530232-b54f62e1-1e18-48c6-a2da-f37ed97fc044.png)

On the front side, I use React and this function component to update and seek the GSAP timeline instance.
![image](https://user-images.githubusercontent.com/24865815/222533445-4ba2dd5f-de54-47fa-86f2-74a04e5225e7.png)

My goal is just to have a kind of dynamic timeline editor where I can hit the clock icon to snap props at a specific mark.
See the Gif example here:
 ![image](https://media.discordapp.net/attachments/1042231099247566849/1080934796664000573/e5yhehf.gif)

Sometimes similar to After Effects or Spine2D.
![image](https://user-images.githubusercontent.com/24865815/222532936-b328534d-c199-4333-8307-d5becdc69f7c.png)

Everything goes fine, but things start to go weird only when I go backward! Why does the overlap not cause any problems in advance but only in reverse?

i hope am more clear about my issu , sry for my poor English and if i explain myself badly :)

**Comment by djmisterjon** [comment]
> Like I said, you certainly should not be creating animations that fight with each other to set the same properties to different values at the same time on the same element.

so the idea would be that each time I add a new key in my timeline editor, I should try loop over all the datas to mutate the durations value ?, and possibly adjust with timescale instead to keep the correlation of the whole timeline..

Did you think is a good idea or yoy maybe have more simple native way with gsap ?
```ts

type PresetLabel = string;
type PresetData = {
	position?:{ x:number, y:number, z:number },

	duration:number,
	timemark:number,
	timescale:number,
}

const testpresets:Map<PresetLabel, PresetData> = new Map([
	// let say on the editor timeline, we batch mark new point in timeline, will need recompute all preset after to avoid overlap maybe ?
	['A', { position:{ x:100, y:100, z:100 }, duration:1, timemark:0, timescale:1 }],
	['B', { position:{ x:200, y:200, z:0 }, duration:1, timemark:0.5, timescale:1 }],
	['C', { position:{ x:400, y:300, z:0 }, duration:1, timemark:0.4, timescale:1 }],
]);

/** refactoring data to avoid overlaps duration, and distribute diff to timescale */
function checkintegrity() {
	// maybe use a user defined duration instead of max timemark + duration ? or this is for "auto" duration mode ?
	const total_expected_duration = [...testpresets].reduce( ( acc, [, data]) => Math.max( acc, data.timemark + data.duration ), 0 );

	console.log( 'before:', [...testpresets]);
	const sorted = structuredClone([...testpresets].sort( ( a, b ) => a[1].timemark - b[1].timemark ) );

	// process to avoid overlap on duration by distributing diff to timescale
	let current:undefined|PresetData = undefined;
	let next:undefined|PresetData = undefined;
	for ( let i = 0, l = sorted.length; i < l; i++ ) {
		current = sorted[i][1];
		next = sorted[i + 1]?.[1];
		if ( next ) {
			const diff_ratio = ( next.timemark - current.timemark ) / current.duration;
			if ( diff_ratio < 1 ) {
				current.duration = next.timemark - current.timemark;
				current.timescale = 1 / diff_ratio;
			}
		} else {
			// last one, check if duration is ok, ? not sure if is nice idea to do that here!
			if ( current.timemark + current.duration > total_expected_duration ) {
				current.duration = total_expected_duration - current.timemark;
			}
		}
	}

	console.log( 'afer:', sorted );
}
checkintegrity();
```

so this can look like this, where all entries datas are fixed to avoid overlaps and distribute ratio to timescale to keep same duration of the scene animations.
Not tested the implementation , but this logic should compatible with gsap behavior ?
![image](https://user-images.githubusercontent.com/24865815/222636775-38fd8fe0-87eb-457d-812d-968e3ccb9c51.png)

**Comment by jackdoyle** [comment]
Sorry, I don't have time to work through your code, figure out the logic and what you're attempting, and then advise a better solution but I will say:

- It seems odd to me that you'd adjust timeScale rather than just setting the duration properly to begin with
- I assume you've got a separate "source of truth" with the data from your visual GUI that needs to get translated into GSAP tweens (rather than treating the GSAP data itself as the "source of truth"). I believe that's what you were showing screen shots of. So I'd imagine that you'd make sure that data is "clean" (no overlaps) before you actually create your animations. If a change is made, perhaps just kill() the old stuff and recreate fresh animations according to the new data. 
- Your editor shouldn't even allow users to create conflicting animations. Don't they just place keyframes and then your code would figure out the durations between those and build out the timeline pretty easily? Why even store "duration" in your data rather than just the timemark of the keyframe and then you calculate the duration by measuring the distance between the timemarks? Just a thought. 

I hope that's at least a little bit helpful. Good luck with the project!
