### ISSUE TITLE
ScrollSmoother - Pull-to-refresh build in browser gesture not working 

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [greensock/GSAP#534]
Mobile Devices (Test on android - chrome + Samsung browser). 

Pull-to-refresh gesture to refresh the page not working on pages with **ScrollSmoother** plugin.

You can try on this page:
https://greensock.com/scrollsmoother/

Not working
![image](https://user-images.githubusercontent.com/16711871/233226647-7c11507a-0633-4216-81e1-93174800bd08.png)

**Comment by jackdoyle** [comment]
Yes, that's because the normalizeScroll() feature is enabled there. As far as I know, it's impossible to accommodate that "pull down to refresh" native feature if we're intercepting touch events to normalize scroll. 

I actually much prefer to disable that "pull to refresh" functionality because it can really mess up scroll-driven effects (technically that'd be a negative scroll position). 

It's a feature, not a bug ;)
