### ISSUE TITLE
Broken callbacks in 3.11.5 after page reload

### ISSUE THREAD

**Issue by its2easy** [greensock/GSAP#538]
Hi, in my project I encountered strange behavior of animations and callbacks when I reload the page near the ScrollTrigger pin area and I found that if I install an earlier version (3.11.4), everything starts working correctly. 
I created a repositoriry with a minimal reproduction and description [https://github.com/its2easy/gsap-callbacks-bug](https://github.com/its2easy/gsap-callbacks-bug). Bugged behavior is reproducing only in chromium-based browsers.
It seems like 3.11.4 non chromium browsers work as they should, and 3.11.4 chromium browsers work strangely but at least they return everything to the correct state.

**Comment by jackdoyle** [comment]
Thanks for putting together that demo, @its2easy. Very helpful. It looks like various browsers fire events in different orders (like a scroll event before or after the scroll restoration...or not at all).

The next release has a workaround that should resolve things. You can preview it at https://assets.codepen.io/16327/ScrollTrigger.min.js

(You may need to clear your cache)

Better?

**Comment by its2easy** [comment]
Thanks you for answering @jackdoyle, I've tried your new ScrollTrigger and all the right callbacks are fired now. But I've found a little oddity in the order of the callbacks. After page refresh near the pin area (but beyond it) `onComplete` of the related timeline is fired before `onEnter` callback of ScrollTrigger:
```
// 1
Timeline onStart
Timeline onComplete

ScrollTrigger onEnter
ScrollTrigger onLeave
```
And if I scroll further from the pin, then after the page refresh the order will be different:
```
// 2
Timeline onStart
ScrollTrigger onToggle
ScrollTrigger onEnter

Timeline onComplete
ScrollTrigger onToggle
ScrollTrigger onLeave
```
This doesn't affect anything in my case, but it seems to me that the 2nd version is more correct. But maybe it should work like this. 

I've found that difference in chrome; in firefox it's always the 1st version of the callbacks order.

**Comment by jackdoyle** [comment]
Yeah, the first behavior is actually correct. The playhead of the timeline gets set during the update of the ScrollTrigger, so any animation (timeline) callbacks would fire, and THEN any ScrollTrigger-related ones would fire. 

The reason the 2nd behavior worked that way is because when the page initially loads the scroll position is at a particular spot and THEN slightly later it gets updated by the browser. Imagine your entire page is 1000px tall in its native state (NO ScrollTriggers). Then you add ScrollTriggers that pin things for 3000px. Well now your overall page will be 4000px. Let's say you scroll to a position of 2000px and then refresh the page...well when the page initially loads, it can't possibly have the scroll position at 2000px because that spot doesn't exist yet. The whole page is only 1000px! The pin spacing that ScrollTrigger adds is what allows that page to expand taller. So initially the ScrollTriggers would render at a lower in-range spot...and then a short time later the browser corrects its scroll position to 2000px since that's now available after the page got taller with pin spacing. 

So the 2nd behavior you described is caused by the fact that the browser initially had the scroll position part-way into that ScrollTrigger...and then it corrected it to be past the end. 

Does that clear things up?

**Comment by its2easy** [comment]
Yes, thanks for your clarification
