### ISSUE TITLE
Scroll Trigger unpin callback function suggestion

### ISSUE THREAD

**Issue by BlazeIsClone** [greensock/GSAP#547]
I'm suggesting an RFC for a function which can pin and unpin from a function callback. Maybe the syntax can look something like this:
```js
myScrollTrigger.unpin();
myScrollTrigger.pin();
```

**Comment by jackdoyle** [comment]
Pinning is actually a very complicated thing to do effectively, so it isn't feasible to offer a function like that. When things get pinned, there is typically pinSpacing that gets added in order to push content below further down to make room for the pinning (avoid overlaps). That, of course, will affect any pinning of THOSE items too, since the scroll position would get further and further down the page as things above get pinned. Part of the magic of ScrollTrigger is that it pre-calculates it all at once inside ScrollTrigger.refresh() so that performance is super smooth. You do the heavy processing once so that it's all super fast thereafter. But it must do the calculations in a very particular order, top-to-bottom in order to make all the appropriate compensations. If you just dynamically pin things whenever you want, that could get very expensive and messy. We'll keep your suggestion in mind, though, and if we ever figure out a really performant and flexible way to offer that, we will!

**Comment by BlazeIsClone** [comment]
@jackdoyle Thanks for your details explanation. I didn't realize that pinning is such an intensive task, so from the information I got from you I dug a bit deeper and got a sense of how the pinsSpacing holds all this together. And I totally agree with your point it feels like it's something which can go way out of hand and possibly introduce a new wave of usability convention problems.
