### ISSUE TITLE
onComplete does not fire if timeScale is set on the last frame.

### ISSUE THREAD

**Issue by Jeaper** [greensock/GSAP#551]
If timeScale is set during the same loop a tween is about to complete
It will Cause it to never call its onComplete event.

I think this only happens if the timescale is called during an event on another tween, but I have not been able to say that for sure, or if on the same RAF is enough.

Recreation:
https://codepen.io/Jesper-Leveau/pen/gOQBpdK

Found during an upgrade of existing project from 1.18.5 to 3.12.2

**Comment by jackdoyle** [comment]
Thanks for the minimal demo, @Jeaper 

This is because you're altering the timeScale such that the completion would be in the PAST. And when adjusting the startTime position in the parent via a timeScale() change, it suppresses events. I'll look into whether or not there's a clean way to accommodate this edge case and NOT suppress events, perhaps with a parameter or something.

**Comment by Jeaper** [comment]
Suggestion: @jackdoyle 
Why does timeScale affect startTime and progress at all?
Should it not just affect how much dt affects the progress in future updates?

**Comment by jackdoyle** [comment]
When you alter the timeScale(), it **MUST** alter the startTime if progress isn't 0, otherwise it'd get out of sync and the playhead would jump. Remember that a child animation's playhead position is controlled by its parent timeline's playhead (so that everything is perfectly in sync). 

For simplicity's sake, let's say you've got a 1-second tween and its startTime is 0 (so it's at the very start of its parent timeline) and then when that tween is at 0.5 (halfway done), you alter the timeScale to be 2 which means the effective duration of that tween becomes 0.5. If we don't update the startTime, then the tween would immediately be at its very end because the parent's playhead is at 0.5 which is where that tween ends if its timeScale is 2 (if it starts at 0 and the native duration is 1 but its timeScale is 2, that means it ends at 0.5). 

So the correct thing to do is alter the startTime to be 0.25 so that the overall progress remains the same (the tween would now be positioned from 0.25 -> 0.75 on its parent timeline). 

Changing the timeScale does not actually affect progress. The reason you saw that in your demo is because of an order-of-execution thing. The first tween updated first...and called its onComplete, and the second tween would have updated next but your first tween read back the 2nd tween's progress BEFORE it had a chance to update. When you altered its timeScale(), you forced an update. 

Make sense? 

I think in the next release, I could allow a suppressEvents parameter on timeScale() just like we do for things like seek(), time(), totalTime(), etc. so that you can tell it specifically that you want callbacks to fire in that case.
