### ISSUE TITLE
Bad `EaseString` type

### ISSUE THREAD

**Issue by FractalHQ** [greensock/GSAP#556]
The `EaseString` type has `string` in the union:

https://github.com/greensock/GSAP/blob/6032c54a21981b389a5f5603a45083f38ed5acf9/types/gsap-core.d.ts#L182

This widens the type and hides the string literals from intellisense:
<img width="319" alt="Screenshot 2023-10-24 at 9 57 23 PM" src="https://github.com/greensock/GSAP/assets/55504972/502f66f3-b192-495c-bc19-111167f01857">

This allows _any_ string and the autocomplete is just random globals.  It should probably be removed altogether and users should use string literals and the const modifier for typesafety... but a compromise would be changing the type to this:

```ts
    //...
    | "sine" | "sine.in" | "sine.out" | "sine.inOut" | ({} & string);
```

By using `({} & string)`, the type will still allow arbitrary strings, but now the autocomplete works:

<img width="312" alt="Screenshot 2023-10-24 at 9 56 28 PM" src="https://github.com/greensock/GSAP/assets/55504972/f007b065-9223-40f2-a65e-4c5f334d19bd">

I was going to submit a PR, but it doesn't look like you guys accept those 😅

**Comment by jackdoyle** [comment]
Interesting, thanks for the suggestion @FractalHQ. I'm not much of a TypeScript guy myself. We definitely need to accept arbitrary strings because that's how CustomEase works (you can assign a name to any ease, or you can even pass 4 comma-delimited bezier numbers). 

So to confirm, you're saying that  ... | ({} & string) will indeed allow arbitrary strings, so we get the best of both worlds and there won't be backward compatibility issues (like if someone isn't running the latest version of TypeScript)?

**Comment by FractalHQ** [comment]
I'm not positive about backwards compatibility -- googling a bit lead me to this post https://stackoverflow.com/a/61048124

The last comment claims the fix doesn't work for `3.8`, while it does in `^4.x`.  I'm not sure if that means it simply doesn't fix autocomplete, or if it explicitly introduces a new compiler error.  I'd assume the former, but testing it out might be warranted if you want to support v3 (although we're on 5.2 these days).

**Comment by jackdoyle** [comment]
Got it, thanks. Seems to still work on 3.x from what I can tell. I'll add this to the next release.

**Comment by raulfdm** [comment]
For reference: https://github.com/sindresorhus/type-fest/blob/main/source/literal-union.d.ts
