### ISSUE TITLE
The fractional container width causes erroneous target transforms

### ISSUE THREAD

**Issue by maxch-aa** [greensock/GSAP#557]
## Isolated case
https://codesandbox.io/s/gsap-issue-fractional-container-width-slj58v?file=/index.html

## Demo
![target transform calculation error](https://github.com/greensock/GSAP/assets/45965282/d6fb3d79-2739-4a3a-b36d-7e09b873c8a9)

**Comment by jackdoyle** [comment]
This illustrates why we always recommend setting transforms through GSAP rather than only using CSS. It eliminates ambiguity, improves performance, and ensures accuracy. You only set them via CSS and normally GSAP can adapt to that without any problem, but you've got an edge case here that perfectly illustrates why it's so important to flow transforms through GSAP.

https://codesandbox.io/s/gsap-issue-fractional-container-width-forked-9lfxzr?file=/index.html

**Explanation:** 
When GSAP starts animating transforms on an element, it has to parse the existing/current ones. If you didn't set those through GSAP (in which case they'd be cleanly cached, easy/fast to read immediately), GSAP has to parse the current values which involves asking the browser to report the computed styles and those are always reported in a matrix() or matrix3d() which has to be decomposed into individual components (x, y, rotation, scaleX, scaleY, etc.). Matrices are inherently ambiguous especially when it comes to rotation and scale. For example, rotation: 180 would produce an identical matrix to scale: -1. 

A ton of effort has gone into making transforms easy to work with in GSAP, so you can animate each component independently (a BIG deal for animators) and you can also combine x/y with xPercent/yPercent for very powerful/convenient effects. 

So in this case, when GSAP parses the current transforms (which you've set via CSS only as translateX(-50%)), the browser reports that in pixels. The browser can't tell GSAP any other unit (that's a browser limitation, not GSAP). So GSAP does its best to pull out that data and make the most sense of it. In this case the x is -150.25. Now GSAP has to decide - should that pixel value go into the normal "x" property or "xPercent"? It only does xPercent if it's exactly -50% of the offsetWidth because that's so common (convenience). But in your scenario, the browser reports the element's offsetWidth as 301 instead of 300.5! So 150.25 is NOT exactly half of 301, thus it assigns it to the normal "x" property (and xPercent would of course be 0). 

Then you animate xPercent to 90. But that's different than the normal "x" property which in this case has a value of -150.25. See the issue? 

It's not really a bug in GSAP - it's much more about the browser rounding values, being limited to reporting things in px, and GSAP is doing its best to figure it out without you following the best practice of setting transform-related values  explicitly through GSAP so that there is no ambiguity at all. 

Does that make sense? 

So the moral of the story is: if you want the most accurate and performant handling of transforms, set them explicitly through GSAP. It's fine if you also set them in CSS just so the initial render looks the way you want, but especially in edge cases like this, just do a gsap.set() to make the values explicit.
