### ISSUE TITLE
GSAP 3.12.3 and 3.12.4 break ScrollTrigger in latest Chrome 

### ISSUE THREAD

**Issue by ynamite** [greensock/GSAP#566]
**EDIT: it seems the issue is specific to my project.** I've created a demo in the following codepen and it seems to work fine in isolation. I'll leave the issue open for now. Close it as you see fit.
https://codepen.io/ynamite/pen/PoVrELW

I upgraded from GSAP 3.11.5 to version 3.12.3 yesterday, in doing so all ScrollTrigger animations started behaving totally bonkers in the latest Chrome version 120.0.6099.109. They continue to work fine in the latest Firefox and Safari respectively.

Today I upgraded to GSAP 3.12.4 released today in hopes of fixing these issues, unfortunately to no avail.
Downgrading to GSAP 3.11.5 fixes the issues for me in Chrome.

**In more detail:**

For example, the following code would cause images to repeatedly flicker in 3.12.4, where in 3.11.5 the animations work as expected. Of course, it could be that my code or project is at fault, but I don't believe it is, since it works in the older version.

```
const images = [...document.querySelectorAll('img')];
if (images) {
    gsap.set(images, {
        scale: 1.1,
        opacity: 0.001
    });
    images.forEach((img) => {
        gsap.to(img, {
            opacity: 1,
            scale: 1,
            duration: 0.6,,
            scrollTrigger: {
                trigger: img,
                start: 'top 80%',
                end: 'bottom top',
                toggleActions: 'play reverse play reverse',
            },
        });
    });
}

```

**Comment by jackdoyle** [comment]
You said in 3.12.x the images "repeatedly flicker", right? Like back and forth, back and forth (same image)? That sounds quite odd to me and I'd love to explore what's going on in-context. But like you said, that CodePen works great so it's tough to troubleshoot. 

I noticed you're animating the very thing that you're using as a trigger which is usually not a good idea because you're moving the very thing whose position is used for the triggering. Typically it's much better to wrap the element and use that wrapper as the trigger (animate the child). 

Does the problem only happen at the very end of the page? I see that you're making the element SMALLER which is maybe affecting the overall scrollable area of the page, thus the page ends up scrolling up due to the animation, triggering the ScrollTrigger to reverse, etc.? (A logic issue) I'm completely guessing here, taking shots in the dark since we can't see a minimal demo but maybe this will give you a nudge in the right direction. 

I also wonder if it's an issue with dynamically-loading images that are causing the page to reflow, triggering layout updates and resizing(?) 

If there's any way to send us a demo that clearly illustrates the issue, that'd be amazingly helpful. Maybe a Stackblitz instead of CodePen? Here's a starter one you can fork: https://stackblitz.com/edit/react-cxv92j

**Comment by ynamite** [comment]
Thank you Jack, I was able to fix the issue. 

The problem was caused by a few things. While the problem did happen with all images, regardless of how far down the images are on the page, it did get increasingly worse the further down the page the images were located, which lead me down the right path. You were right on track with the issue being caused by lazy loading and/or dynamically loading other content (SVGs in my case). By making sure that every image and element had its proper dimensions or aspect ratios before initializing Scroll Trigger, I was able to get rid of the problem entirely.

By the way, in the real life example I'm not animating the element which is also the trigger, in the code pen I just simplified the example a little too much. 

It's strange though that this problem occurred so prominently in newer GSAP versions. But yeah, thanks a lot.

One more thing, why do you prefer Stackblitz over Codepen nowadays?

**Comment by jackdoyle** [comment]
Thanks for getting back to us with your results/solution. Like you, I am also curious about why older versions seemed to work better for you but that's difficult for me to explore without a minimal demo that clearly illustrates the issue. If you're ever able to isolate things in a minimal demo I'd be happy to take a peek. 

Oh, and we don't favor Stackblitz over Codepen (quite the opposite actually) - it's just that some people find CodePen challenging when they're using a framework like React, Vue, Next.js, etc. or if they've got a setup that requires multiple files or compile steps so I was just offering Stackblitz in case that was easier for you.

**Comment by ynamite** [comment]
No problem! :) 

I believe the main issue was that the flickering images (the ones I wanted to animate with Scroll Trigger) had no intrinsic width/height on page load/when initializing ScrollTrigger (due to lazy loading). So the flickering might have happened because to ScrollTrigger the start and end values of the image were very close to each other, due to the low height (maybe even zero height?). 
Additionally, there were other images above and below those images, that also didn't have their dimensions properly set. As for why it worked in earlier GSAP versions I don't know.

I'll see if I can whip up a demo that illustrates the problem clearly in the coming days.
