### ISSUE TITLE
Flickering phenomenon in 3.12.4v

### ISSUE THREAD

**Issue by namoong0917** [greensock/GSAP#567]
Hi GSAP Team 😀
![gsap-](https://github.com/greensock/GSAP/assets/103318401/92a8b382-fec2-4677-b853-6306e0b54a52)

codepen URL : https://codepen.io/pen?template=QWobwoL

I wanted to quickly fix the sections, so I used `duration: { min: .1, max: .1 }` 
It's fine in version 3.11, but a problem occurs in version 3.12.4

**OS** : Windows
**Chrome version** : 120.0.6099.130

**Comment by jackdoyle** [comment]
There was a regression in 3.12.3 that's already fixed in the upcoming release which you can preview at:
https://assets.codepen.io/16327/ScrollTrigger.min.js

Here it is in your pen:  
https://codepen.io/GreenSock/pen/zYbGvoy?editors=1010

Better?

It only affected ScrollTriggers that had snapping AND a numeric scrub value. Sorry about any confusion there.

**Comment by namoong0917** [comment]
Thank you. Have a good day!
