### ISSUE TITLE
Is it possible to use GSAP within a Web Worker?

### ISSUE THREAD

**Issue by gabrielecirulli** [greensock/GSAP#570]
Hi, I'm using Pixi.js for a basic scene and want to animate the sprites with GSAP. But I'm using a Web Worker and OffscreenCanvas (which Pixi.js supports) and it seems GSAP doesn't work here.

My issue is with the Pixi plugin registration. I use `gsap.registerPlugin(PixiPlugin);`. In `_createPlugin`, it calls `_windowExists()`, which returns false in a Worker, preventing plugin registration.

I'm not sure if GSAP works in this setup, as I can't get past this problem. I'm wondering if there's Worker support at all or if I'm overlooking something.

**Comment by jackdoyle** [comment]
Hm, do you have a minimal demo you can share that clearly illustrates the issue? I was always under the impression that it didn't make sense to do any kind of animation work inside a worker because the entire point is to have it driven by the requestAnimationFrame loop that's on the main thread, but it looks like there is support for requestAnimationFrame in workers. 

I just updated the next release of PixiPlugin so that it doesn't require the window (you can preview the minified version at https://assets.codepen.io/16327/PixiPlugin3.min.js) 

And I also made improvements to the core to accommodate this: https://assets.codepen.io/16327/gsap-latest-beta.min.js

If you can share a minimal demo so that we can verify that it works in your particular scenario, that'd be super helpful. Maybe  a CodePen or Stackblitz?

**Comment by jackdoyle** [comment]
This should be more doable in the latest release, but let us know if you run into any trouble. A minimal demo would be super helpful.

**Comment by gabrielecirulli** [comment]
Thank you for looking into this! For now I decided to use [popmotion](https://popmotion.io/) instead, but in summary what I'm trying to do is render an animated game entirely within a Web Worker using [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas). Pixi.js is capable of running within a Worker, so GSAP would have to run there too in order not to have animation data cross the bridge every frame. 

What this essentially means is that the rendering loop runs in a completely isolated thread than the main browser thread. This theoretically helps with performance because your renderer and animations wouldn't have to share resources with other scripts.

**Comment by jackdoyle** [comment]
Thanks for the added details. Did you try the latest release of GSAP?

**Comment by gabrielecirulli** [comment]
No, I won’t be testing it out as I’ve found a good fit with popmotion and
the deadline I have doesn’t leave much space for experimentation. But I
will keep it in mind for future projects and maybe this tweak will help
other folks who find the issue!

Thank you!
