### ISSUE TITLE
What is the performance bottleneck of GSAP?

### ISSUE THREAD

**Issue by botoxparty** [greensock/GSAP#573]
Hey!

Currently just bored and experimenting with the performance limitations of GSAP. I was wondering what the known limitations are?

I've tried creating my own easing functions and using WebAssembly to calculate them however the benchmarks are the same. 

So i wonder, are there any other critical functions that can have their processing offloaded to WebAssembly to improve performance? 

Also, What opportunities are out there for someone to make a contribution to GSAP?

**Comment by jackdoyle** [comment]
There isn't really a "limitation" in GSAP - it's mostly about the browser and device that's running on that dictate how far you can push things. 

Performance is a very deep topic, but...

1. The bottleneck is almost always **graphics rendering** in the browser. In other words, GSAP itself might take up 0.5% of the overall load, whereas all the other graphics-related tasks and event processing eats up the other 99.5% (hypothetically), so even if you magically discovered a way to make GSAP twice as fast, you'd never even notice the difference because the overall impact would be miniscule. I'd focus your attention on minimizing the load on the browser graphics rendering.
2. I highly doubt that offloading parts to WebAssembly would have any noticeable impact. Ultimately everything ties back to the main thread where the screen updates occur anyway. If you, for example, try to push all the easing calculations over to a different thread, there's still going to be extra overhead involved in getting that data over to the other thread and then pulling it back and populating the right values. Whatever you gain by offloading things to another thread might be lost by the extra coordination overhead. 

If you've got ideas for improving GSAP, we're always open to listening. Feel free to post your suggestions here or (better yet) in our active forums at https://gsap.com/community

Thanks!
