### ISSUE TITLE
onStart callback is not called after pause 

### ISSUE THREAD

**Issue by salomvary** [greensock/GSAP#574]
Although the documentation does not explain when the `onStart` callback is supposed to be called, I assume every time the timeline changes from "paused" to "not paused". However, the callback does not seem to be called `play()` follows a `pause()`.

In the example below, I'd expect `onStart` to be called twice, but it's only called one time.

```js
const timeline2 =  gsap.timeline({
  paused: true,
  onStart: () => console.log('start 2')
}).to(".box2", { 
  x: 200,
  duration: 5
});

timeline2.play()

setTimeout(() => {
  timeline2.pause()
  setTimeout(() => {
    timeline2.play()
  }, 1000)
}, 1000)
```

Playground: https://codepen.io/salomvary/pen/xxBYBwG?editors=1111

**Comment by jackdoyle** [comment]
Hi @salomvary The docs clearly state: 

> onStart: A function to call when the animation begins (when its time changes from 0 to some other value which can happen more than once if the tween is restarted multiple times).

So this is **NOT** anytime the animation changes from paused to unpaused. It's specifically for when the playhead moves from 0 (the start) to something else. 

Does that clear things up?

**Comment by salomvary** [comment]
Hi @jackdoyle, thanks for the quick response!

> The docs clearly state:
> 
> > onStart: A function to call when the animation begins (when its time changes from 0 to some other value which can happen more than once if the tween is restarted multiple times).

Oh interesting, I've tried searching for "onStart" to find some clues, without any success:
https://gsap.com/search?q=onStart&ctx=docs

Which documentation page is this on? I'd be very keen to learn what callbacks are available and what their semantics are.

> 
> So this is **NOT** anytime the animation changes from paused to unpaused. It's specifically for when the playhead moves from 0 (the start) to something else.
> 
> Does that clear things up?

Understand. Is there a callback I can use to detect the "unpausing" of the timeline, no matter where the playhead was?

**Comment by salomvary** [comment]
Oh, found the "missing" documentation page: https://gsap.com/docs/v3/GSAP/Timeline#special-properties-and-callbacks

Seems like there is no straightforward way to detect "resume after pause" using a callback.

**Comment by jackdoyle** [comment]
No, from an engineering standpoint, that didn't seem wise because: 

- GSAP has a very flexible, modular architecture which allows you to nest things as deeply as you want, so you can have timelines within timelines, etc. You can independently `pause()` anything. What if you `pause()` a parent timeline? That'd technically sorta behave as if the child is paused even though it's not (since the parent's playhead is what controls the child's playhead normally). If you checked the child's `paused()` state, it'd say `false` which is accurate, but since an ancestor is paused, the playhead isn't moving. So should that fire your proposed onPause/onResume? It gets very fuzzy.
- You can `pause()` an animation and then use ANOTHER animation to tween its playhead! So technically it is paused, but it looks like it's playing because another tween is animating its playhead. Would that fire your onPause/onResume callback?
- What if the playhead moves by some other call, like `animation.totalTime(4)` - would that fire the onPause/onResume? 

Since what you seem to be asking for would only get triggered by your own code (like wherever you put `animation.pause()`/`resume()`), it seems much more appropriate for you to just call your function at that point in your code. In other words, whatever you're trying to have onStart call...just put that into your codebase wherever you've got `.play()`/`.resume()`. See what I mean?

**Comment by salomvary** [comment]
Oh wow, I was not aware of the possibility of independently pausing/resuming nested timelines :)

>  it seems much more appropriate for you to just call your function

Yep, that should be the way to go.

Thanks a lot for explaining everything and for all the work you put into making this library.

**Comment by jackdoyle** [comment]
Absolutely! Happy to help. 

Enjoy the tools.
