### ISSUE TITLE
Gsap markers position not working on scroll+refresh | versions > 3.12.2

### ISSUE THREAD

**Issue by samuel-clara** [greensock/GSAP#575]
The current version of gsap ScrollTrigger 3.12.5 and also versions after 3.12.2 seem to not correctly handle trigger markers when refreshing the browser window after scrolling to a different position then the top of the page. With gsap ScrollTrigger 3.12.2 all is working fine.

If I load a page, scroll after the trigger element, refresh the browser window and scroll back to the top, the start marker changes it's position. I add two screenshots of first load and load after scroll down.

![load](https://github.com/greensock/GSAP/assets/11197191/25f0887d-ff6c-4f03-8008-fcb45b33b283)
![load after scroll](https://github.com/greensock/GSAP/assets/11197191/ea94144f-d098-4b52-b758-3bdf614bf5ea)

I've tried to create a basic codepen for this but codepen does not maintain the scroll position after refresh so it's impossible to recreate this on codepen.

**Comment by jackdoyle** [comment]
Hm, I can't seem to reproduce this problem and nobody else has reported such a thing - would you mind providing a CodePen demo even if it's not possible to actually see the issue in CodePen's normal iframe-based mode? We can test it in CodePen's "debug" view (I think a paid package is required to do that on CodePen, but it's fine if you don't have it - we can test in ours). It just really helps to see your setup, as there must be something that's different about your setup than what we're trying on our end to reproduce it. 

And you're saying that the actual problem isn't really the markers themselves - it's miscalculating the ScrollTrigger start/end positions (even with markers disabled), right? 

Thanks!

**Comment by jackdoyle** [comment]
Hm, I'd love to see your demo. Typically ScrollTrigger forces scroll-behavior to "auto" but maybe you overrode that? 

The reason scroll-behavior: smooth is so problematic is that it's sorta like setting a CSS transition on something you're animating with JS; when the JS sets the new style on every tick, the browser is like "NOPE! I'm not gonna apply that right away...I'm gonna gradually do it over time" which totally gets in the way and also hurts performance. Part of what ScrollTrigger must do is temporarily set the scroll position to the very top in order to properly do all calculations especially with any pinning, and then it restores the original scroll position. So scroll-behavior: smooth would basically mean the browser says "NOPE!" when ScrollTrigger moves the scroll position temporarily. 

Does that clear things up? I'm still curious to see a demo if you're willing to provide one.

**Comment by jackdoyle** [comment]
Yeah, I can't reproduce that even with "Disable Cache" enabled in the network tab.

**Comment by themorgansmake** [comment]
Sorry, I know this is closed but just wanted to say thanks and also that I've just been stumped by this problem.

I had the exact same issue that my "scroll-behavior: smooth" on the html element was causing my pinned element to miscalculate it's start and end triggers when refreshing the page.

This was on a very simple:

`ScrollTrigger.create({
   trigger: ".pinned-background",
   start: "top top",
   end: "bottom bottom",
   pin: ".left",
});`

I noticied that if you refreshed the page outside of the triggers view ( most top part of site say ) it would likely be fine. That makes good sense above regarding what scroll behavior is doing, so likely is clashing.

Can also confirm that downgrading to 3.12.2 worked whilst leaving the scroll behavior on.

**Comment by jackdoyle** [comment]
Hi @themorgansmake - do you have a minimal demo illustrating the issue (like a CodePen or Stackblitz)? And are you saying that the latest version of ScrollTrigger/GSAP does NOT work the way you'd expect? It is definitely not a good idea to have scroll-behavior: smooth on a site that's using ScrollTrigger. Or at least disable that when doing a ScrollTrigger.refresh().

**Comment by mezzoEmrys** [comment]
Ran into this issue on a clean install Firefox on Windows as well

I was following the example on this codepen from [this thread](https://gsap.com/community/forums/topic/38765-images-fade-inout-acording-to-text-scrolling/)

[https://codepen.io/GreenSock/pen/gOeMJOV](https://codepen.io/GreenSock/pen/gOeMJOV)

but had `scroll-behavior: smooth;` enabled. When you add `scroll-behavior: smooth` to the `html,body` rule in that codepen, then scroll down slightly and resize the window left-right, you can observe the "start" marker moves upwards equivalent to the percentage of viewport height that you scrolled down. Scrolling back up to the top and resizing again will place the "start" marker back where it belongs.

**Comment by jackdoyle** [comment]
You should never set scroll-behavior: smooth on a ScrollTrigger-driven site because it's sorta like setting a CSS transition on something that you're also animating with GSAP - when GSAP tries to make a change, the browser is like "NOPE! I won't do that...instead, I'm gonna drag that change out over the course of X seconds..." As a part of its refresh calculations, it needs to set the scroll position back to 0 temporarily, do its measurements, and set it back. But if you've got scroll-behavior: smooth, the browser refuses to honor that, so it throws off the calculations. You're welcome to use ScrollSmoother, of course.
