### ISSUE TITLE
The Rotation animation has some problems in Flip

### ISSUE THREAD

**Issue by zbysir** [greensock/GSAP#585]
https://codepen.io/zbysir/pen/mdZONRg

It cannot animate normally. It seems that the calculated position (x, y) caused by the rotation angle is incorrect.

Again, the animation will only work properly if you click to switch states again before completing the last animation.

**Comment by jackdoyle** [comment]
Ah, that looks like one of the common mistakes - you should **ALWAYS** set transform-related values via GSAP. In your demo, you were only doing it via CSS. In order to maximize performance and avoid ambiguity inherent in transform matrices, GSAP caches transform-related values. You can, of course, bust that if you want by using clearProps. 

For example:
```javascript
gsap.set(squares, {clearProps: true});
```

https://codepen.io/GreenSock/pen/oNrBGNR?editors=1010

Here are some of the common mistakes: 
https://gsap.com/resources/mistakes#not-setting-all-transforms-with-gsap

Does that clear things up?

**Comment by zbysir** [comment]
Before using GSAP, I controlled element properties through CSS, and FLIP is so easy to use (just three lines of code) that after I started using FLIP, I didn't set properties using gsap.set anymore.

Setting properties with GSAP can be a bit cumbersome, especially when there are many elements involved, which makes FLIP seem less straightforward. Nevertheless, both GSAP and FLIP are already quite good.

There’s also a small issue: I’ve seen several places in the documentation mentioning “Set any transform-related values (x, y, scale, rotation, etc.) [directly via GSAP](https://gsap.com/resources/mistakes#transforms),” but I don’t understand what problems it could cause if you don’t do it this way. Perhaps you could write a demo (similar to the erroneous examples I mentioned) to illustrate the issue.

Thank you very much for helping me with my problem. @jackdoyle

**Comment by jackdoyle** [comment]
> Setting properties with GSAP can be a bit cumbersome, especially when there are many elements involved, which makes FLIP seem less straightforward. Nevertheless, both GSAP and FLIP are already quite good.

Hm, I'm curious if you could provide an example where it's cumbersome to set properties with GSAP. It should be super simple. Did you realize you can set properties on many elements with a single line of GSAP code? 

> I’ve seen several places in the documentation mentioning “Set any transform-related values (x, y, scale, rotation, etc.) [directly via GSAP](https://gsap.com/resources/mistakes#transforms),” but I don’t understand what problems it could cause if you don’t do it this way.

That's what is explained in the article I linked to. https://gsap.com/resources/mistakes/#not-setting-all-transforms-with-gsap

GSAP caches transform-related values on each element that it touches (including via Flip plugin). So you were setting transforms via GSAP/Flip...and then you were shifting the DOM around in a way that'd cause other CSS rules to apply to the elements (altering their appearance/transforms OUTSIDE of GSAP), and then you were expecting GSAP to use those new CSS-driven values instead of the cached ones on those elements. 

For example, let's say you set rotation to 45 via GSAP, but then you manually remove the inline styles and apply a class that sets transform: rotate(-30deg) (without using GSAP). Then if you gsap.to("#el", { rotation: 90}) - well, when GSAP reads the current value for that tween, it'll use the cached value which is 45 (not -30). 

Again, the key is to always set transform-related values via GSAP. -OR- if you need to do it outside of GSAP, make sure you clear them explicitly via GSAP, like gsap.set(el, { clearProps: "transform" })

Does that clear things up?

**Comment by zbysir** [comment]
Clear and clear, thank you. @jackdoyle
